Line 109: [GL1 Error] Invalid bandmode (%d)
Line 160: [GL1 Error] Invalid band (%d)
Line 221: [GL1 Error] Invalid channelType (%d)
Line 269: [GL1 Error] Invalid channelType (%d)
Line 306: [GL1 Error] Invalid Cipher silAlgorithm (%d)
