Line 16: Enter svc_log_file_save() msg_type(%d)
Line 114: svc_log_file_save() rfs_open_file(%d)
Line 119: svc_log_file_save() max_file_size(%d) log size(%d)
Line 173: Enter svc_log_save() msg_type(%d)
Line 182: svc_log_save() gettime(%d %d %d)
