Line 171: [RF ET][ET S5000AP EVT0] Tx_DAC_Set_ET_DAC CC Info Error: err (0x%x), tx_path info (%d)
Line 188: [RF ET][ET S5000AP EVT0] Tx_DAC_Set_ET_DAC DAC Mode error : dac mode (%d)
Line 228: [RF ET][ET S5000AP EVT0] Tx_DAC_Set_ET_DAC CC Info Error: err (0x%x), tx_path info (%d)
Line 300: [RF ET][ET S5000AP EVT0] TxF_Filter_Set_ET_IN_DATA_SEL CC Info Error : err (0x%x), tx_path info (%d)
Line 334: [RF ET][ET S5000AP EVT0] TxF_Filter_Read_ET_IN_DATA_SEL CC Info Error : err (0x%x), tx_path info (%d)
Line 382: [RF ET][ET S5000AP EVT0] TxF_SW_RESETn is zero!! (0x%x)
Line 402: [RF ET][ET S5000AP EVT0] TxF_SW_RESETn is zero!! (0x%x)
Line 406: [RF ET][ET S5000AP EVT0] SW_RESETn (0x%x)
Line 547: [RF ET][ET S5000AP EVT0] RF_Modem_ET_TxF_Filter_Config_CFR CC Info Error : err (0x%x), tx_path info (%d)
Line 611: [RF ET][ET S5000AP EVT0]RF_Modem_ET_TxF_Filter_Config_Filter CC Info Error : err (0x%x), tx_path info (%d)
Line 651: [RF ET][ET S5000AP EVT0] RF_Modem_ET_TxF_Filter_Main_Delay_SW_EN CC Info Error : err (0x%x), tx_path info (%d)
Line 708: [RF ET][ET S5000AP EVT0]TxF_Filter_Config_ET_Block CC Info Error : err (0x%x), tx_path info (%d)
Line 736: [RF ET][REG CTRL][DELAY] Fractional delay is not valid! (%d)
Line 741: [RF ET][REG]SET delay %d/%d/%d
Line 763: [RF ET][ET S5000AP EVT0] TxF_Filter_Set_Delay CC Info Error : err (0x%x), tx_path info (%d)
Line 828: [RF ET][REG CTRL][DELAY] Fractional delay is not valid! err (0x%x), EFD (%d)
Line 834: [RF ET][REG CTRL][DELAY] Main path bulk delay is not valid! err (0x%x), MBD (0x%x), MBD_I (%d), MBD_Q (%d)
Line 875: [RF ET][ET S5000AP EVT0] Fractional delay is not valid! : err (0x%x), tx_path info (%d)
Line 881: [RF ET][REG CTRL][DELAY] Main path bulk delay is not valid! err (0x%x), MBD (0x%x), MBD_I (%d), MBD_Q (%d)
Line 891: [RF ET][ET S5000AP EVT0] TxF_Filter_Set_Delay CC Info Error : err (0x%x), tx_path info (%d)
Line 939: [RF ET] : Negative ET SF data -> Check the ET SF Data : err (0x%x)
Line 974: [RF ET][ET S5000AP EVT0]TxF_Filter_Write_ET_SF_LUT CC Info Error : err (0x%x), tx_path info (%d)
Line 1016: [RF ET][ET S5000AP EVT0]TxF_Filter_Config_SF_LUT CC Info Error : err (0x%x), tx_path info (%d)
Line 1022: [RF ET][ET S5000AP EVT0]TxF_Filter_Config_SF_LUT Config LUT Error : err (0x%x), tx_path info (%d)
Line 1049: [RF ET][REG]SET LUT Num %d
Line 1063: [RF ET][ET S5000AP EVT0]TxF_Filter_Config_DPD_LUT CC Info Error : err (0x%x), tx_path info (%d)
Line 1069: [RF ET][ET S5000AP EVT0]TxF_Filter_Config_DPD_LUT Config LUT Error : err (0x%x), tx_path info (%d)
Line 1260: [RF ET][ET S5000AP EVT0]TxF_Filter_Write_DPD_Value CC Info Error : err (0x%x), tx_path info (%d)
Line 1309: [RF ET][S355 REG] DPD Data :index(%3d) AM:%4d ,PM:%4d
Line 1429: [RF ET][ET S5000AP EVT0]TxF_Filter_Write_DPD_Value_All CC Info Error : err (0x%x), tx_path info (%d)
Line 1465: [RF ET][ET S5000AP EVT0]TxF_Filter_Set_ET_DAC_IN_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1502: [RF ET][ET S5000AP EVT0]TxF_Filter_Read_ET_DAC_IN_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1540: [RF ET][ET S5000AP EVT0]Tx_4G_MOD_GAIN_Set_ET_IFFT_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1580: [RF ET][ET S5000AP EVT0]Tx_4G_MOD_GAIN_Read_ET_IFFT_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1674: [RF ET][ET S5000AP EVT0]TxF_Filter_Set_ET_DGC_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1714: [RF ET][ET S5000AP EVT0]TxF_Filter_Read_ET_DGC_Gain CC Info Error : err (0x%x), tx_path info (%d)
Line 1743: [RF ET][REG]SET gain AMG1:0x%x AMG2:0x%x ENVG1:0x%x ENVG2:0x%x
Line 1764: [RF ET][ET S5000AP EVT0]TxF_Filter_Set_ET_GainBlock CC Info Error : err (0x%x), tx_path info (%d)
Line 1816: [RF ET][ET S5000AP EVT0]TxF_Filter_Read_ET_GainBlock CC Info Error : err (0x%x), tx_path info (%d)
Line 1842: [RF ET][ET S5000AP EVT0]TxF_Filter_Set_ET_LUT_Sel CC Info Error : err (0x%x), tx_path info (%d)
Line 1938: [RF ET][ET S5000AP EVT0]TxF_Filter_Generate_1tone CC Info Error : err (0x%x), tx_path info (%d)
Line 2000: [RF ET][ET S5000AP EVT0]Tx_Filter_CLK_on_off CC Info Error : err (0x%x), tx_path info (%d)
Line 2207: [RF ET][ET S5000AP EVT0]TxF_Filter_Write_DPD_Value_by_Tool CC Info Error : err (0x%x), tx_path info (%d)
Line 2273: [RF ET][ET S5000AP EVT0]TxF_Filter_Write_ET_SF_LUT_by_Tool CC Info Error : err (0x%x), tx_path info (%d)
Line 2444: [RF ET][ET S5000AP EVT0]TxF_Filter_Read_DPD CC Info Error : err (0x%x), tx_path info (%d)
Line 2512: [RF ET][ET S5000AP EVT0]TxF_Filter_Read_SF CC Info Error : err (0x%x), tx_path info (%d)
Line 2553: [ET ERROR][ET S5000AP EVT0] Get_Reg_Info_Index :: No Proper Register! reg_type(%d)
Line 2599: [RF ET][ET S5000AP EVT0]RegCtrl_CLK_Gating :: TxF_Tx_Clock Gating Error : err (0x%x)
Line 2610: [RF ET][ET S5000AP EVT0]RegCtrl_CLK_Gating :: TxF_Tx_Clock Gating Error : err (0x%x)
Line 2619: [RF ET][Modem Ctrl] ClkGating :: Check RAT - rat (%d)
Line 2623: [RF ET][Modem Ctrl] ClkGating :: rat (%d), on_off(%d)
Line 2661: [RF ET] : Modem_ctrl_DPD :: Check RAT - rat (%d)
Line 2673: [RF ET] : RegCtrl_DPD :: Check lut idx - lut_num (%d)
Line 2676: [RF ET][Modem Ctrl] DPD :: rat (%d), lut_num (%d)
Line 2715: [RF ET] : Modem_ctrl_SF :: Check RAT - rat (%d)
Line 2726: [RF ET] : RegCtrl_SF :: Check lut idx - lut_num (%d)
Line 2729: [RF ET][Modem Ctrl] SF :: rat (%d), lut_num (%d)
Line 2772: [RF ET] : Modem_ctrl :: Check RAT - rat (%d)
Line 2803: [RF ET][Modem Ctrl] GainTable :: AMG1 (0x%x), AMG2 (0x%x), ENVG1 (0x%x), ENVG2 (0x%x), ENVOffset (0x%x), reg_mode(0x%x)
Line 2834: [RF ET] : Modem_ctrl :: Check RAT - rat (%d)
Line 2845: [RF ET][Modem Ctrl] LUT SEL :: DLUT (%d), SFLUT (%d), reg_mode (0x%x) -> DPD(0x%x) SF(0x%x)
Line 2884: [RF ET][Modem Ctrl] Delay :: rat (%d), RW_Mode[0/1(Read/Write)] (%d), MB (0x%x), EB (0x%x), EF (%d)
Line 2926: [RF ET][Modem Ctrl] ET DAC :: on_off (%d), et_dac_mode_val (0x%x), et_ctrl (0x%x)
Line 3081: [RF ET][Modem Ctrl] ET_IN_DATA_SEL :: et_in_date_sel (%d)
Line 3117: [RF ET][Modem Ctrl] RegCtrl_ET_DAC_IN_GAIN :: et_dac_in_gain (0x%x)
Line 3154: [RF ET][Modem Ctrl] RegCtrl_IFFT_GAIN :: ifft_slot0 (0x%x), ifft_slot1 (0x%x)
Line 3183: [RF ET][Modem Ctrl] RegCtrl_IFFT_GAIN_SLO :: ifft_gain_tx1 (0x%x), ifft_gain_tx2 (0x%x)
Line 3190: [RF ET][Modem Ctrl] RegCtrl_IFFT_GAIN_SLO :: ifft_gain_tx1 (0x%x), ifft_gain_tx2 (0x%x)
Line 3229: [RF ET][Modem Ctrl] RegCtrl_DGC_GAIN :: dgc_gain0 (0x%x), dgc_gain1 (0x%x)
Line 3326: [RF ET] RegCtrl_Config_Main_Path_Block :: error (0x%x)
Line 3399: [RF ET] RegCtrl_Config_ET_Path_Block :: error (0x%x)
Line 3426: [RF ET][Modem Ctrl] Generate_1tone :: tx_path (%d), on_off (%d)
Line 3466: [RF ET] : RegCtrl_Write_DPD_by_Tool :: Check RAT - rat (%d)
Line 3480: [RF ET] : RegCtrl_Write_DPD_by_Tool :: err (0x%x), Write_DPD_Value_by_Tool Fail
Line 3485: [RF ET] : RegCtrl_Write_DPD_by_Tool :: err (0x%x), Check lut_num (%d)
Line 3488: [RF ET][ET S55AP] RegCtrl_Write_DPD_by_Tool :: rat (%d), lut_num (%d)
Line 3530: [RF ET] : RegCtrl_Write_SF_by_Tool :: Check RAT - rat (%d)
Line 3544: [RF ET] : RegCtrl_Write_SF_by_Tool :: err (0x%x), Write_SF_LUT_by_Tool Fail
Line 3549: [RF ET] : RegCtrl_Write_SF_by_Tool :: err (0x%x), Check lut_num (%d)
Line 3552: [RF ET][ET S55AP] RegCtrl_Write_SF_by_Tool :: rat (%d), lut_num (%d)
Line 3589: [RF ET] : RegCtrl_Read_DPD :: Check RAT - rat (%d)
Line 3599: [RF ET] : RegCtrl_Read_DPD :: Read_DPD Fail
Line 3604: [RF ET] : RegCtrl_Read_DPD :: Read_DPD Fail
Line 3607: [RF ET][ET S55AP] RegCtrl_Read_DPD :: rat (%d), lut_num (%d)
Line 3646: [RF ET] : RegCtrl_Read_SF :: Check RAT - rat (%d)
Line 3656: [RF ET] : RegCtrl_Read_SF :: Write_SF_LUT_by_Tool Fail
Line 3661: [RF ET] : RegCtrl_Read_SF :: Check lut_num (%d)
Line 3664: [RF ET][ET S55AP] RegCtrl_Read_SF :: rat (%d), lut_num (%d)
Line 3701: [RF ET] : Modem_ctrl_DPD :: Check RAT - rat (%d)
Line 3712: [RF ET] : RegCtrl_DPD :: Check lut cnt - lut_cnt (%d)
Line 3715: [RF ET][Modem Ctrl] DPD :: rat (%d), lut_cnt (%d)
Line 3752: [RF ET][Modem Ctrl] CFR_Signal_Sel :: tx_path (%d), en_sel (%d), sw_en (%d)
Line 3757: [RF ET][Modem Ctrl] CFR_Signal_Sel :: tx_path (%d), en_sel (%d), sw_en (%d)
Line 3762: [RF ET][ET S5000AP EVT0]CFR_Signal_Sel CC Info Error : err (0x%x), tx_path info (%d)
Line 3804: [RF ET][Modem Ctrl] Get_Reg_Addr :: REG TYPE(%d) BASE(0x%x) ADDR(0x%x)
Line 3811: [ET ERROR][ET S5000AP EVT0] Get_Reg_Addr :: Out of Range Error : Addr(0x%x) Range(0x%x ~ 0x%x)
Line 3817: [ET ERROR][ET S5000AP EVT0] Get_Reg_Addr :: Get reg info index Error
Line 3879: [RF ET] : Modem_ctrl_CFR :: Check RAT - rat (%d)
Line 3913: [RF ET][ET S5000AP EVT0] RegCtrl_Read_Swap_Status :: ANT SWAP ET PATH 0x%x
Line 3944: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 3950: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 3956: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 3962: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 3968: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 3974: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 3980: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 3986: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 3992: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 3998: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4004: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4007: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4015: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4021: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4027: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4033: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4039: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4045: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4051: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4057: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4063: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4069: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4075: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4078: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4086: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4092: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4098: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4103: [RF ET][ET S5000AP] Reg Status: Addr(0x%x) - Data(0x%x) 
Line 4156: [RF ET][ET S5000AP] 40M Tone gen: idx(%d) - Data(%d) 
Line 4267: [RF ET][ET S5000AP EVT0] RegCtrl_Set_DAC_BW_setting
