Line 110: Fail to allocate memory!
Line 148: Fail to send message!
Line 153: Fail to build message!
Line 181: [MSG<=] SRM_IMS_START_SVE_RSP
Line 247: [MSG<=] SRM_IMS_STOP_SVE_RSP
Line 313: [MSG<=] SRM_IMS_CHANGE_SVE_RSP
Line 443: [MSG<=] SRM_IMS_OPTION_SET_RSP
Line 539: [MSG<=] SRM_IMS_RECEIVE_DTMF
Line 606: [MSG<=] SRM_IMS_RTP_RX_TIMEOUT_IND
Line 662: [MSG<=] SRM_IMS_RTP_RX_TIMEOUT_CLEAR_IND
Line 718: [MSG<=] SRM_IMS_RTCP_RX_TIMEOUT_IND
Line 774: [MSG<=] SRM_IMS_RTCP_RX_TIMEOUT_CLEAR_IND
Line 844: [MSG<=] SRM_IMS_RTCP_RX_SR_IND
Line 916: [MSG<=] SRM_VCG_CALLESTABLISH_REQ
Line 952: [SESSION] CALLESTABLISH_REQ : bw(%d)freq(%d)br(%u)DTX(%u)
Line 959: [SESSION] CALLESTABLISH_REQ : Chawarerecv(%d)IoMode(%d)SendChannelType(%u)RecvChannelType(%u)
Line 1037: [SESSION] ALTERCODEC_REQ : bw(%d)freq(%d)br(%u)DTX(%u)
Line 1043: [SESSION] ALTERCODEC_REQ : Chawarerecv(%d)IoMode(%d)SendChannelType(%u)RecvChannelType(%u)
Line 1120: [MSG<=] VCG_CALLACTIVATE_IND : cid(%u), freq(%d)
Line 1156: [MSG<=] SRM_VSS_RX_TTY_NTF : utf8Octet(0x%x)
Line 1185: Unexpected RTT Event!
Line 1214: [MSG<=] SRM_SRM_TERMINATE_SESSION_IND : index(%u)
Line 1251: [CALLBACK] socket(%d) event (%d)
Line 1283: [MSG<=] SRM_IMS_FIRST_RTP_IND
Line 1345: [MSG<=] VCG_CALL_QUALITY_INFO_IND
Line 1368: [MSG<=] SRM_SRM_REDUNDANCY_REQ
Line 1400: [MSG<=] SRM_SRM_FRAME_AGGREGATION_REQ
Line 1432: [MSG<=] SRM_SRM_CODEC_MODE_REQ
Line 1464: [MSG<=] Send SRM_SRM_EVS_PRIMARY_RATE_REQ
Line 1496: [MSG<=] SRM_SRM_EVS_BANDWIDTH_REQ to SRM
Line 1528: [MSG<=] Send SRM_SRM_EVS_CHANNEL_AWARE_REQ
Line 1560: [MSG<=] SRM_SRM_EVS_PRIMARY_TO_EVS_AMRWBIO_REQ
Line 1592: [MSG<=] SRM_SRM_EVS_AMRWBIO_TO_EVS_PRIMARY_REQ
Line 1622: [MSG<=] SRM_SRM_UL_CODEC_MODE_IND_REQ
Line 1651: [MSG<=] SRM_SRM_ALTER_CODEC_IND_REQ
Line 1682: [MSG<=] SRM_SRM_CHANGE_BITRATE_REQ
