Line 65: >>> GHAL_Stub called L1AlNvramInitialise()
Line 72: >>> GHAL_Stub called CfL1BgSystemInitialise()
Line 79: >>> GHAL_Stub called CfL1BgSystemActive()
Line 85: >>> GHAL_Stub called L1BgIdleInitialise()
Line 90: >>> GHAL_Stub called L1TimersInitialise()
Line 95: >>> GHAL_Stub called L1BgInitTcbAllocation()
Line 100: >>> GHAL_Stub called L1FrInitTriggerControl()
Line 111: >>> GHAL_Stub called L1FrNullInit()
