Line 4: [I][[TCS_DFC_TYPE]]		: 0x%x
Line 6: [I][[TCS_OPT_CARRIER_TYPE]]		: 0x%x
Line 8: [I][[TCS_OPT_CARRIER_TYPE]]		: 0x%x
Line 10: [I][[TCS_MAKE_TYPE]]		: 0x%x
Line 12: [I][[TCS_MAKE_TYPE]]		: 0x%x
Line 13: [I][[TCS_KT_LTE_ROAMING]]		: 0x%x
Line 15: [I][[TCS_CSG_SUPPORT]]		: 0x%x
Line 17: [I][[TCS_CSG_SUPPORT]]		: 0x%x
Line 19: [I][[TCS_UPGRADE_SRVCC]]		: 0x%x
Line 21: [I][[TCS_UPGRADE_SRVCC]]		: 0x%x
Line 23: [I][[TCS_UPGRADE_RSRVCC]]		: 0x%x
Line 25: [I][[TCS_UPGRADE_RSRVCC]]		: 0x%x
Line 27: [I][[TCS_UPGRADE_ISR]]		: 0x%x
Line 29: [I][[TCS_UPGRADE_ISR]]		: 0x%x
Line 31: [I][[TCS_USIM_MIGRATION]]		: 0x%x
Line 33: [I][[TCS_USIM_MIGRATION]]		: 0x%x
Line 35: [I][[TCS_DISABLE_GSM_SEARCH]]		: 0x%x
Line 37: [I][[TCS_DISABLE_GSM_SEARCH]]		: 0x%x
Line 39: [I][[TCS_DSDS_TYPE]]		: 0x%x
Line 41: [I][[TCS_DSDS_TYPE]]		: 0x%x
