Line 839: L1CfgMonitorRSSI sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 874: L1CfgMonitorRSSI no sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 970: L1CfgMonitorRSSI_RFCAL startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1056: L1CfgMonitorRSSI_RFCAL startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1147: L1CfgMonitorRSSI_Irat startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1417: L1CfgStartFbAcquire sniff startOffset [%d] startdsp [%d]
Line 1440: L1CfgStartFbAcquire no sniff startOffset [%d] startdsp [%d]
Line 1506: L1CfgStartFbAcquire no sniff startOffset [%d] startdsp [%d]
Line 1777: L1CfgSbAcquire no sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1875: L1CfgPtmSbAcquire startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1986: L1CfgSbAcquire sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 2011: L1CfgSbAcquire no sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
