Line 177: rrc_CellChangeOrderFail_setInterRatChangeFailure: inappropriate ChangeFailCause
Line 195: rrc_CellChangeOrderFail_setInterRatChangeFailure: invalid ChangeFailCause
Line 235: rrc_CellChangeOrderFail_setInterRatChangeFailure: inappropriate ChangeFailCause
Line 243: rrc_CellChangeOrderFail_setInterRatChangeFailure: invalid ChangeFailCause
