Line 188: rrc_HandoverFromUtranFail_setInterRatHandoverFailure: inappropriate HandoverFailCause
Line 230: rrc_HandoverFromUtranFail_setInterRatHandoverFailure: invalid HandoverFailCause
Line 272: rrc_HandoverFromUtranFail_setInterRatHandoverFailureWithProto: inappropriate HandoverFailCause
Line 280: rrc_HandoverFromUtranFail_setInterRatHandoverFailureWithProto: invalid HandoverFailCause
Line 407: rrc_HandoverFromUtranFail_setEutraMessage: Failed to Free ptr
