Line 280: QuickSleep activation request (enableStatus:%d)
Line 293: QuickSleep deactivated (bitmap:0x%x), previous1(%d), previous2(%d)
Line 585: RXF_SYNC_4G : 0x%x
Line 596: QS_CONDITION_DYNAMIC, disableConditionCount(%d), cond_dci/cond_crc/snr/dop(%04x), gap/csirs/mbsfn/crok/sf05(0x%05x), pseudoDci/dynamic/rstd/meas/sync(%05x)
Line 637: QSleep status changed: TTI/Status(%d/%d), (%d/%d)
Line 753: [AS] RSRP timer(%d,%d)
Line 781: [AS] U/L RSRP (%d,%d), diff(%d), status(%d), RxRsrpOffset(%d,%d), TAS_enb(%d)
Line 895: [AS] L/R RSRP (%d,%d), diff(%d), status(%d), RxRsrpOffset(%d,%d), meas_idx(%d)
Line 956: [4RxD] CC0 RSRP (%d,%d,%d,%d), diff(%d,%d), meas_idx(%d)
Line 1149: ONE_RX CHECK_signalQuality, CurMode(%d), SelectedMode(%d), disableConditions(%d), caOn/crcBad/lowSnr(%03x), filteredSinr(%d), ant_sw_txpwr_en(%d), maxpwr_tworx(%d)
Line 1168: IPC:RX MODE_CHANGE_NOTIFY (to ARM) - antennaMode(%d), caOn/crcBad/lowSnr(%03x), filteredSinr(%d)
Line 1195: [4RxD] Periodic 4Rx monitoring is skipped by DataInactiveStatus(%d) or MIMO Max(%d) or csi_static(%d)
Line 1207: [4RxD] Periodic 4Rx monitoring, AS_RX2_flag(%d), FourRx_RSRP_flag(%d), rxmode_bitmap(%d), FourRx_monitoring_trigger(%d)
Line 1214: [4RxD] div_enb(%d), div_num(%d), pActiveCC->num(%d)
Line 1409: [4RxD] sinr_path (%d,%d,%d,%d), sinr_2rx(%d,%d,%d)
Line 1410: [4RxD] CC%d scheduling rate (%d), rb_size_ratio(%d), isVoLTEcall(%d), ueCategory(%d), mimo_max(%d), rxmode_bitmap(%d)
Line 1517: [4RxD] 4X4MIMO is configured and waiting for changing to 4Rx, check(%d), check timer(%d)
Line 1525: [4RxD] 4X4MIMO is configured and waiting for changing to 4Rx, check(%d), check timer(%d)
Line 1653: [4RxD] 4RxD is triggered to improve OTA performance.
Line 1670: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1675: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1696: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1701: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1720: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1725: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1737: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1742: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1757: [4RxD] 4RxD is maintained to improve OTA performance.
Line 1795: [4RxD] 4RxD is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1800: [4RxD] 4RxD is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1832: IPC:RX MODE_CHANGE_NOTIFY (to ARM): %d, CC%d cur_rx_mode: %d
Line 1835: IPC:RX MODE_CHANGE_NOTIFY is skipped (to ARM), CC%d cur_rx_mode: %d
Line 1870: [4RxD] best 2Rx condition check, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d)
Line 1877: Best2RxSel: cck(%d), cand_bitmap(0x%x)
Line 1896: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1901: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1916: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1921: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1937: [4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
Line 1942: [4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
