Line 333: [LAA] subframeConfigcurrent(%d), subframeConfignext(%d)
Line 365: [LAA](F) Configuration is mismatched next(%d),current(%d) 
Line 371: [LAA] CCH_ParseLAASubframeConfiguration subframeconfig(%d), subframeconfig_forLAA(%d), endsubframeNminus1sf(%d), subframeConfignext(%d), endsubframeDetected(%d)
Line 429: [LAA] PCell or PScell is not possible for LAA Scell, cc_idx(%d), cell_group(%d)
Line 432: IPC: LAA Config for CC(%d) valid(%d), subframeStartPosition_r13(%d), laa_SCellSubframeConfig_r13(%d)
Line 496: IPC: LAA Release cc_idx(%d), g_laa_valid(%x)
Line 556: [LAA] DCI is discarded
Line 613: (I)[LAA] dci1c_decinfo.reg(0x%x), subframeConfigforLAA(%d), cce_idx(%d), agg(%d), data(0x%x,0x%x), detectionmode(%d)
Line 619: [LAA] UE did not receive the DCI Format 1C subframeConfigcurrent encoded CC-RNTI, use subframeConfignext(%d), subframeConfigforLAA(%d)
Line 701: [LAA] nslot=1, cc_idx(%d) LAA_DETECTION_MODE_CCx(0x%x), CCx_LAA_FAD_CON0(0x%x), CCx_LAA_FAD_SERTHR(0x%x)
Line 708: [LAA] nslot=0, cc_idx(%d) LAA_DETECTION_MODE_CCx(0x%x)
Line 754: [LAA] nslot = 1, CCx_LAA_INIT_TTI(0x%x)
Line 839: LAA_SetSubframeCeParam(end):CC:%d, sfk:%d, subframeConfigforLAA:%d, Current(sfType/nCrs23/nCrs01):%x
Line 888: [LAA] nslot = 1, LAA_CTRL_CH_DEMAPPING(0x%x)
Line 925: [LAA] slot=%d,cgk=%d,CCH_WGEN_CC_INFO_M(S)CG(0x%x),CCH_WGEN_CC_INFO_LAA_M(S)CG(0x%x)
Line 1018: [LAA] nslot = 1, RADDR_LAA_CRS_CE_INFO(0x%x)
Line 1049: [LAA] start_partial_on(%d),end_partial_on(%d),laa_pbch_off(%d),laa_sync_off(%d),end_symbol_num(%d),tdd_sync_tti_on(%d)
Line 1055: [LAA] RADDR_LAA_SF_INFO(0x%x)
Line 1096: [LAA] No DCI and CRS, cc_idx(%d), current_TTI_metric(%d), metric_prv_TTI(%d)
Line 1137: [LAA] nslot = 1, MCG_LAST_RS_CHK(0x%x), SCG_LAST_RS_CHK(0x%x)
Line 1176: [LAA] cc_idx(%d), dmtc_en(%d) dmtc_start(%d), sfn_cur(%d), ret_val(0x%x)
Line 1260: [LAA] (f)TTI Mismatched! LAA TTI(%d), Current TTI(%d) 
Line 1285: [LAA] (f)LAA Interrupt is occured at wrong RTG! rtg(%d) 
Line 1290: [LAA] LAA Interrupt atti(%d), slot(%d), CG(%d), MCG_DL_DETECT_MON(0x%x), SCG_DL_DETECT_MON(0x%x)
Line 1328: [LAA] cc_idx(%d), slot(%d) p_laa_cfg->cell_group(%d), CCx_LAA_SLEEP_STATE(0x%x), dci_detected(%d), detectionmode(%d), detected_slot(%d) 
Line 1366: LAA on-state(%d), det_mode(%d), dci_detected(%d), det_run_cnt(%d), fa_chk_cnt(%d)
Line 1397: [LAA] Status: slot(0), active:CC1-CC7(%07d), cell_group:(%07d), sleep_state:(%07d), dci_detected:(%05d), detectionmode:(%07d), detected_slot:(%07d), sfcfg_LAA:(%07x)
Line 1409: [LAA] Status: slot(1), active:CC1-CC7:(%07d), is_dmtc:(%07d), sleep_state:(%07d), dci_detected:(%05d), detectionmode:(%07d), detected_slot:(%07d), sfcfg_LAA:(%07x)
Line 1524: DMTC info setup, dmtc_en: %d, dmtc_start: %d
