Line 253: CSI_GetBwPartIdx: BWP_IDX calculation for invalid PCR. cc_idx(%d), proc_idx(%d), set_idx(%d), atti(%d)
Line 514: (F) Subframe set configuration exist, but no CQI,PMI,RI config index. (R10)
Line 558: (F) Subframe set configuration exist, but no CQI,PMI,RI config index. (R11)
Line 746: CC(%d), CSI_SetConfig
Line 771: (F) CSI config: invalid subframe pattern. length(%d,%d)
Line 839: (F) CSI config: Ignore CSI process list. cc_idx(%d), trans_mode(%d), setup(%d), num_proc(%d)
Line 866: (F) CSI config: invalid RI-reference CSI-process. cc_idx(%d), process(%d), rrcp_id(%d)
Line 933: (F) CSI config: invalid periodic-proc-id. cc_idx(%d), process(%d), preiodic-proc-id(%d)
Line 941: (F) CSI_SetConfig: CoMP + eICIC. cc_idx(%d), process(%d), idx2_valid(%d), p_c_AndCBSR_r11_cnt(%d)
Line 1091: CSI - add reconfig flag (CC%d), 0x%X + 0x%X -> 0x%X
Line 1551: (F) CSI updateparam: invalid CSI-RS/IM id. cc_idx(%d), csirs_id(%d), csiim_id(%d)
Line 1562: (F) CSI updateparam: TM9. CSI-RS not configured. cc_idx(%d)
Line 1583: (F) CSI updateparam: invalid number of CRS antenna ports. cc_idx(%d), n_antP(%d)
Line 1669: (F) SetAperiodicCsiRequest with CSIREQ0. cc_idx(%d), info(0x%x), m3(%d)
Line 1767: (F) aperiodic request - out of subfrmset1/2. cc_idx(%d), proc_idx(%d), trg_atti(%d)
Line 1780: (F) aperiodic request - out of subfrmset1/2. cc_idx(%d), proc_idx(%d), trg_atti(%d)
Line 1936: (F) CSI_Pa: abnormal index. cc/proc/set(%d,%d,%d), pa(%d), offset(%d), tbl_idx(%d,%d)
Line 2160: (F) CSI_TTI_CONFIG: missing(%d)/matched(%d). valid(%02d), sn(%06d), ref(0x%05x,0x%05x), ref_rd(0x%05x)
Line 2167: (F) CSI_TTI_CONFIG: no matched config. valid(%02d), sn(%06d), bmp(0x%05x,0x%05x), ref_bmp(0x%05x)
