Line 88: [VHM_SetCpuClk_PerCodecPath_Engine] cur_path (0x%X) CallCodecType (0x%X) 
Line 159: [VHM_SetCpuClk_PerCodecPath] enForce (0x%X) 
Line 171: [VHM_SetCpuClk_PerCodecPath] - c2c_vss_send_ipc - enForce (0x%X) 
Line 185: [VHM_SetCpuClk_PerCodecPath] - c2c_vss_send_ipc - enForce (0x%X) 
Line 206: [VHM_SetCpuBUSC_PerCodecPath_Engine] cur_path (0x%X) CallCodecType (0x%X) 
