Line 103: fachControllerArray[0] == NULL
Line 282: tphy_CFachResources insttance mem allocation failed
Line 321: Warning: FachConfigMsg configMsg->payload.sccpchInfo.CommonTimeSlotInfo.TFCI_Coding out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 336: Warning: FachConfigMsg configMsg->payload.sccpchInfo.CommonTimeSlotInfo.RepPeriod out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 349: Warning: FachConfigMsg configMsg->payload.sccpchInfo.CommonTimeSlotInfo.InterleavingMode out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 362: Warning: FachConfigMsg configMsg->payload.sccpchInfo.IndividualTimeSlotInfo.timeslotNumber out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 376: Warning: FachConfigMsg configMsg->payload.sccpchInfo.IndividualTimeSlotInfo.MidambleShiftandBurst.MidambleAllocationMode out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 389: Warning: FachConfigMsg configMsg->payload.sccpchInfo.IndividualTimeSlotInfo.MidambleShiftandBurst.MidambleConfiguration out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 404: Warning: FachConfigMsg configMsg->payload.sccpchInfo.IndividualTimeSlotInfo.MidambleShiftandBurst.MidambleShift out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 420: Warning: FachConfigMsg configMsg->payload.numOfDlCtfc out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 437: Warning: FachConfigMsg configMsg->payload.dlCtfcArray[i] out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 452: Warning: FachConfigMsg configMsg->payload.numOfFach out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 472: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.trChType out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 487: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.tti out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 500: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.channelCoding out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 513: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.rateMatchingArgument out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 526: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.crcSize out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 539: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.semiStaticInfo.codingRate out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 554: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.dynamicInfo.numOfTfTableEntries out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 571: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.dynamicInfo.tfTableEntryArray[j].numOTblocks out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 584: Warning: FachConfigMsg configMsg->payload.fachInfoArray[i].dlTrCh.dynamicInfo.tfTableEntryArray[j].tBlockSize out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 606: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.tti out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 619: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.channelCoding out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 632: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.rateMatchingArgument out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 645: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.crcSize out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 658: Warning: FachConfigMsg configMsg->payload.pchInfo.dlTrCh.semiStaticInfo.codingRate out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
Line 674: Warning: FachConfigMsg configMsg->payload.fachOccasionInfo.fachOccasionCycleLengthCoef out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/pchFach/src/tphy_CFachResources.c Line %d
