Line 154: [SIL_ConvertIratSchTtpcom] SchResult_p->fnOffset(%d), SchResult_p->NetworkFrNum(%d)
Line 223: SIL_schIratInitialise()
Line 243: SIL_AbortSchActivities()
Line 261: SIL_DestroyIratSchResource for arfcn(%d),address(%x)
Line 302: SILSCH: Allocating SIL object at address(%x)
Line 345: [IRATAFC] update ARFCNDATA ARFCN (%d), FreqOffsetHz (%d)
Line 397: SILSCH: object allocated for arfcn(%d)
Line 437: No valid data from the arfcn store for ARFCN(%d)
Line 447: ARFCN(%d), isPcsBandUsed = %d, AGC rssi %d
Line 497: SILSCH: resource alloc fail for arfcn(%d)
