Line 103: StartupInit: %d Failed
Line 140: Create: No Timer available(%s,%d)
Line 156: TimId(%d) created(%d/%d)(%s,%d)
Line 187: Start: TimID(%d) deleted(%s,%d)
Line 193: Start: TimID(%d) running(%s,%d)
Line 206: Start: TimID(%u) duration(%d)(%s,%d)
Line 211: Start: Failed to start TimID(%u)(%s,%d)
Line 217: Start: Invalid TimId(%d)(%d)(%s,%d)
Line 243: Stop: Invalid TimId(%d)(%s,%d)
Line 254: Stop TimId(%d)(%s,%d)
Line 259: Stop: TimId(%d) Stop Fail(%s,%d)
Line 264: Stop: TimId(%d) deleted(%s,%d)
Line 268: Stop: TimId(%d) Inactive(%s,%d)
Line 272: Stop: TimId(%d) Invalid state(%d)(%s,%d)
Line 323: BDA_HandleTimerExpiry: Unexpected TimerId(%d)
