Line 18: [RF API] %s: %s, %s start
Line 22: [RF API] %s finish
Line 40: [RF API] %s start
Line 46: [RF API] %s finish
Line 64: [RF API] %s start
Line 68: [RF API] %s finish
Line 90: [RF ET] %s : err(invalid band - %d)
Line 94: [RF API] %s start
Line 98: [RF API] %s finish
Line 106: [RF API] %s start
Line 110: [RF API] %s finish - 0x%x
Line 121: [RF API] %s start
Line 129: [RF API] %s finish - 0x%x
Line 152: [RF ET] %s : err(invalid band - %d)
Line 156: [RF API] %s start
Line 161: [RF API] %s finish
Line 183: [RF API] %s start
Line 187: [RF API] %s finish
Line 206: [RF API] %s start
Line 210: [RF API] %s finish
Line 230: [RF API] %s start
Line 234: [RF API] %s finish
Line 255: [RF API] %s start
Line 259: [RF API] %s finish
Line 279: [RF API] %s start
Line 283: [RF API] %s finish
Line 304: [RF API] %s start
Line 308: [RF API] %s finish
Line 333: [RF API] %s start
Line 337: [RF API] %s finish
Line 361: [RF API] %s start
Line 365: [RF API] %s finish
Line 389: [RF API] %s start
Line 393: [RF API] %s finish
Line 416: [RF API] %s: start
Line 420: [RF API] %s: finish
Line 440: [RF API] %s: start
Line 444: [RF API] %s: finish
Line 461: [RF API] %s: start
Line 465: [RF API] %s: finish
Line 470: [RF API] %s: start
Line 475: [RF API] %s: finish
Line 482: [RF API] %s: start
Line 486: [RF API] %s: finish
Line 493: [RF API] %s: start
Line 497: [RF API] %s: finish
Line 502: [RF API] %s: start
Line 506: [RF API] %s: finish
Line 511: [RF API] %s: start
Line 515: [RF API] %s: finish
Line 520: [RF API] %s: start
Line 524: [RF API] %s: finish
Line 529: [RF API] %s: start
Line 533: [RF API] %s: finish
Line 539: [RF API] %s: start
Line 543: [RF API] %s: finish
Line 548: [RF API] %s: start
Line 552: [RF API] %s: finish
Line 558: [RF API] %s: start
Line 562: [RF API] %s: finish
Line 568: [RF API] %s: start
Line 572: [RF API] %s: finish
Line 578: [RF API] %s: start
Line 582: [RF API] %s: finish
Line 588: [RF API] %s: start
Line 593: [RF API] %s: finish
Line 599: [RF API] %s: start
Line 604: [RF API] %s: finish
Line 626: [RF API] %s start
Line 630: [RF API] %s finish
