Line 44: [SIPC_1_SOUND] Tx NS_SOUND_VOLUME_REQ (usVolumeLevel=%d)
Line 44: [SIPC_0_SOUND] Tx NS_SOUND_VOLUME_REQ (usVolumeLevel=%d)
Line 68: [SIPC_1_SOUND] Tx NS_SOUND_MIC_MUTE_REQ (ucMuteStatus=%d)
Line 68: [SIPC_0_SOUND] Tx NS_SOUND_MIC_MUTE_REQ (ucMuteStatus=%d)
Line 93: [SIPC_1_SOUND] Tx NS_SOUND_PATH_REQ (ucPath=%d, ucMode=%d)
Line 93: [SIPC_0_SOUND] Tx NS_SOUND_PATH_REQ (ucPath=%d, ucMode=%d)
Line 119: [SIPC_1_SOUND] Tx NS_SOUND_LOOPBACK_REQ (ucStatus=%d, ucPath=%d)
Line 119: [SIPC_0_SOUND] Tx NS_SOUND_LOOPBACK_REQ (ucStatus=%d, ucPath=%d)
Line 144: [SIPC_1_SOUND] Tx NS_SOUND_VIDEO_CALL_REQ (ucVtMode=%d)
Line 144: [SIPC_0_SOUND] Tx NS_SOUND_VIDEO_CALL_REQ (ucVtMode=%d)
Line 168: [SIPC_1_SOUND] Tx NS_SOUND_CLOCK_REQ (ucStatus=%d)
Line 168: [SIPC_0_SOUND] Tx NS_SOUND_CLOCK_REQ (ucStatus=%d)
Line 192: [SIPC_1_SOUND] Tx NS_SOUND_TWO_MIC_SOL_CON_REQ (ucMode=%d)
Line 192: [SIPC_0_SOUND] Tx NS_SOUND_TWO_MIC_SOL_CON_REQ (ucMode=%d)
Line 218: [SIPC_1_SOUND] Tx NS_SOUND_DHA_CON_REQ (ucMode=%d, ucSelect=%d)
Line 218: [SIPC_0_SOUND] Tx NS_SOUND_DHA_CON_REQ (ucMode=%d, ucSelect=%d)
Line 245: [SIPC_1_SOUND] Tx NS_SOUND_DMV_MODE_REQ (ucMode=%d, ucStatus=%d)
Line 245: [SIPC_0_SOUND] Tx NS_SOUND_DMV_MODE_REQ (ucMode=%d, ucStatus=%d)
Line 270: [SIPC_1_SOUND] Tx NS_SOUND_CLK_MODE_REQ (Mode=%d)
Line 270: [SIPC_0_SOUND] Tx NS_SOUND_CLK_MODE_REQ (Mode=%d)
Line 295: [SIPC_1_SOUND] Tx NS_SOUND_AUDIO_DSP_SET_REQ (ucCallMode=%d)
Line 295: [SIPC_0_SOUND] Tx NS_SOUND_AUDIO_DSP_SET_REQ (ucCallMode=%d)
