Line 49: [SIPC_1_SAT] Tx NS_USAT_SEND_REGISTRATION_REQ
Line 49: [SIPC_0_SAT] Tx NS_USAT_SEND_REGISTRATION_REQ
Line 75: [SIPC_1_SAT] Tx NS_USAT_SEND_ENVELOPE_REQ (Envelope Cmd Len=%d)
Line 75: [SIPC_0_SAT] Tx NS_USAT_SEND_ENVELOPE_REQ (Envelope Cmd Len=%d)
Line 105: [SIPC_1_SAT] Tx NS_USAT_SEND_TERMINAL_RESPONSE_REQ (Terminal Cmd Rsp Len=%d)
Line 105: [SIPC_0_SAT] Tx NS_USAT_SEND_TERMINAL_RESPONSE_REQ (Terminal Cmd Rsp Len=%d)
Line 140: [SIPC_1_SAT] Tx NS_USAT_GET_IMAGE_CLUT_REQ (type=0x%X, FilePath=0x%X, len=%d, offset=0x%X)
Line 140: [SIPC_0_SAT] Tx NS_USAT_GET_IMAGE_CLUT_REQ (type=0x%X, FilePath=0x%X, len=%d, offset=0x%X)
Line 169: [SIPC_1_SAT] Tx NS_USAT_GET_IMSI
Line 169: [SIPC_0_SAT] Tx NS_USAT_GET_IMSI
Line 192: [SIPC_1_SAT] Tx NS_SAT_SIM_INITIATE_EVENT
Line 192: [SIPC_0_SAT] Tx NS_SAT_SIM_INITIATE_EVENT
Line 227: [SIPC_1_SAT] Tx NS_USAT_REFRESH_VOTE_RESULT:RefreshVoteRsp(%d)
Line 227: [SIPC_0_SAT] Tx NS_USAT_REFRESH_VOTE_RESULT:RefreshVoteRsp(%d)
