Line 47: [SIPC_1_SAT] Rx NS_USAT_SEND_REGISTRATION_RSP
Line 47: [SIPC_0_SAT] Rx NS_USAT_SEND_REGISTRATION_RSP
Line 60: [SIPC_1_SAT] Rx NS_USAT_SEND_ENVELOPE_RSP (Result=0x%X)
Line 60: [SIPC_0_SAT] Rx NS_USAT_SEND_ENVELOPE_RSP (Result=0x%X)
Line 82: [SIPC_1_SAT] Rx NS_USAT_SEND_TERMINAL_RESPONSE_RSP (Result=0x%X)
Line 82: [SIPC_0_SAT] Rx NS_USAT_SEND_TERMINAL_RESPONSE_RSP (Result=0x%X)
Line 104: [SIPC_1_SAT] Rx NS_USAT_GET_IMAGE_CLUT_RSP (Result=0x%X)
Line 104: [SIPC_0_SAT] Rx NS_USAT_GET_IMAGE_CLUT_RSP (Result=0x%X)
Line 126: [SIPC_1_SAT] Rx NS_USAT_PROACTIVE_CMD_IND
Line 126: [SIPC_0_SAT] Rx NS_USAT_PROACTIVE_CMD_IND
Line 141: [SIPC_1_SAT] Rx NS_USAT_CALL_CONTROL_RESULT_IND
Line 141: [SIPC_0_SAT] Rx NS_USAT_CALL_CONTROL_RESULT_IND
Line 157: [SIPC_1_SAT] Rx NS_USAT_REFRESH_STATE_IND : state %d, mode %d
Line 157: [SIPC_0_SAT] Rx NS_USAT_REFRESH_STATE_IND : state %d, mode %d
Line 189: [SIPC_1_SAT] [SIPC_SAT] SIM initialization isn't completed yet
Line 189: [SIPC_0_SAT] [SIPC_SAT] SIM initialization isn't completed yet
Line 222: [SIPC_1_SAT] Rx NS_USAT_SEND_IMSI_REFRESH (IMSI Len=%d)
Line 222: [SIPC_0_SAT] Rx NS_USAT_SEND_IMSI_REFRESH (IMSI Len=%d)
Line 223: [SIPC_1_SAT] IMSI
Line 223: [SIPC_0_SAT] IMSI
Line 238: [SIPC_1_SAT] Invalid IMSI length
Line 238: [SIPC_0_SAT] Invalid IMSI length
Line 253: [SIPC_1_SAT] Sending PB init Complete Status
Line 253: [SIPC_0_SAT] Sending PB init Complete Status
Line 270: [SIPC_1_SAT] Rx NS_USAT_REFRESH_VOTE_IND. Mode : [%d]
Line 270: [SIPC_0_SAT] Rx NS_USAT_REFRESH_VOTE_IND. Mode : [%d]
