Line 46: [SIPC_1_EMBMS] Tx NS_EMBMS_SERVICE_REQ (state=0x%X)
Line 46: [SIPC_0_EMBMS] Tx NS_EMBMS_SERVICE_REQ (state=0x%X)
Line 71: [SIPC_1_EMBMS] Tx NS_EMBMS_SESSION_REQ (state=0x%X)
Line 71: [SIPC_0_EMBMS] Tx NS_EMBMS_SESSION_REQ (state=0x%X)
Line 106: [SIPC_1_EMBMS] Tx NS_EMBMS_SESSION_LIST_REQ (state=0x%X)
Line 106: [SIPC_0_EMBMS] Tx NS_EMBMS_SESSION_LIST_REQ (state=0x%X)
Line 123: [SIPC_1_EMBMS] Tx NS_EMBMS_SIG_STRENGTH_REQ
Line 123: [SIPC_0_EMBMS] Tx NS_EMBMS_SIG_STRENGTH_REQ
Line 139: [SIPC_1_EMBMS] Tx NS_EMBMS_NTWRK_TIME_REQ
Line 139: [SIPC_0_EMBMS] Tx NS_EMBMS_NTWRK_TIME_REQ
