Line 32: [SIPC_1_SAP] Rx NS_SIM_TRANSFER_ATR_RSP (Result Code=0x%X, ATR Len=%d)
Line 32: [SIPC_0_SAP] Rx NS_SIM_TRANSFER_ATR_RSP (Result Code=0x%X, ATR Len=%d)
Line 69: [SIPC_1_SAP] Rx NS_SIM_CONNECTION_RSP (Type %d, Status=%d)
Line 69: [SIPC_0_SAP] Rx NS_SIM_CONNECTION_RSP (Type %d, Status=%d)
Line 86: [SIPC_1_SAP] Rx NS_SIM_TRANSFER_APDU_RSP (Result %d, Rsp Len=%d)
Line 86: [SIPC_0_SAP] Rx NS_SIM_TRANSFER_APDU_RSP (Result %d, Rsp Len=%d)
Line 107: [SIPC_1_SAP] Rx NS_SIM_POWER_CHANGE_RSP (Result %d, Msg Id=%d)
Line 107: [SIPC_0_SAP] Rx NS_SIM_POWER_CHANGE_RSP (Result %d, Msg Id=%d)
Line 119: [SIPC_1_SAP] Rx NS_SIM_TRANSFER_CARD_READER_STATUS_RSP (Result %d, Status=0x%X)
Line 119: [SIPC_0_SAP] Rx NS_SIM_TRANSFER_CARD_READER_STATUS_RSP (Result %d, Status=0x%X)
