Line 40: [SIPC_1_NS] Tx NS_POWER_CONSUMPTION_REQ
Line 40: [SIPC_0_NS] Tx NS_POWER_CONSUMPTION_REQ
Line 61: [SIPC_1_NS] Tx NS_DRX_SETTING_SET_REQ
Line 61: [SIPC_0_NS] Tx NS_DRX_SETTING_SET_REQ
Line 84: [SIPC_1_NS] Tx NS_DRX_SETTING_GET_REQ
Line 84: [SIPC_0_NS] Tx NS_DRX_SETTING_GET_REQ
