Line 35: [SIPC_1_SAP] Tx NS_SIM_CONNECTION_REQ (Type=%d)
Line 35: [SIPC_0_SAP] Tx NS_SIM_CONNECTION_REQ (Type=%d)
Line 55: [SIPC_1_SAP] SAP connection type (0x%x -> 0x%X)
Line 55: [SIPC_0_SAP] SAP connection type (0x%x -> 0x%X)
Line 64: [SIPC_1_SAP] Tx NS_SIM_TRANSFER_APDU_REQ (Data len=%d)
Line 64: [SIPC_0_SAP] Tx NS_SIM_TRANSFER_APDU_REQ (Data len=%d)
Line 87: [SIPC_1_SAP] Tx NS_SIM_POWER_CHANGE_REQ (Type=0x%X)
Line 87: [SIPC_0_SAP] Tx NS_SIM_POWER_CHANGE_REQ (Type=0x%X)
Line 110: [SIPC_1_SAP] POWER_CHANGE_REQ (0x%x -> 0x%X)
Line 110: [SIPC_0_SAP] POWER_CHANGE_REQ (0x%x -> 0x%X)
Line 118: [SIPC_1_SAP] Tx NS_SIM_TRANSFER_CARD_READER_STATUS_REQ
Line 118: [SIPC_0_SAP] Tx NS_SIM_TRANSFER_CARD_READER_STATUS_REQ
