Line 38: [SIPC_1_IMS] Rx NS_IMSCC_CHNL_GET_RSP (Channel Count=%d)
Line 38: [SIPC_0_IMS] Rx NS_IMSCC_CHNL_GET_RSP (Channel Count=%d)
Line 59: [SIPC_1_IMS] Rx NS_IMSCC_CHNL_SET_RSP (channel id=%d, result=0x%X)
Line 59: [SIPC_0_IMS] Rx NS_IMSCC_CHNL_SET_RSP (channel id=%d, result=0x%X)
Line 84: [SIPC_1_IMS] Rx NS_IMSCC_CODEC_GET_RSP (channel id=%d, codec count=%d)
Line 84: [SIPC_0_IMS] Rx NS_IMSCC_CODEC_GET_RSP (channel id=%d, codec count=%d)
Line 146: [SIPC_1_IMS] Rx NS_IMSCC_CODEC_SET_RSP (channel id=%d, result=0x%X)
Line 146: [SIPC_0_IMS] Rx NS_IMSCC_CODEC_SET_RSP (channel id=%d, result=0x%X)
Line 169: [SIPC_1_IMS] Rx NS_IMSCC_RTP_MEDIA_START_RSP (channel id=%d, result=0x%X)
Line 169: [SIPC_0_IMS] Rx NS_IMSCC_RTP_MEDIA_START_RSP (channel id=%d, result=0x%X)
Line 203: [SIPC_1_IMS] Rx NS_IMSCC_RTP_MEDIA_CHANGE_RSP (channel id=%d, result=0x%X)
Line 203: [SIPC_0_IMS] Rx NS_IMSCC_RTP_MEDIA_CHANGE_RSP (channel id=%d, result=0x%X)
Line 226: [SIPC_1_IMS] Rx NS_IMSCC_RTP_MEDIA_STOP_RSP (channel id=%d, result=0x%X)
Line 226: [SIPC_0_IMS] Rx NS_IMSCC_RTP_MEDIA_STOP_RSP (channel id=%d, result=0x%X)
Line 249: [SIPC_1_IMS] Rx NS_IMSCC_DTMF_SET_RSP (channel id=%d, result=0x%X)
Line 249: [SIPC_0_IMS] Rx NS_IMSCC_DTMF_SET_RSP (channel id=%d, result=0x%X)
Line 272: [SIPC_1_IMS] Rx NS_IMSCC_DTMF_RSP (channel id=%d, result=0x%X)
Line 272: [SIPC_0_IMS] Rx NS_IMSCC_DTMF_RSP (channel id=%d, result=0x%X)
Line 296: [SIPC_1_IMS] Rx NS_IMSCC_STAT_GET_RSP (channel id=%d)
Line 296: [SIPC_0_IMS] Rx NS_IMSCC_STAT_GET_RSP (channel id=%d)
Line 320: [SIPC_1_IMS] Rx NS_IMSCC_OPTION_SET_RSP (channel id=%d, result=0x%X)
Line 320: [SIPC_0_IMS] Rx NS_IMSCC_OPTION_SET_RSP (channel id=%d, result=0x%X)
Line 343: [SIPC_1_IMS] Rx NS_IMSCC_RTP_TIMEOUT_IND (channel id=%d)
Line 343: [SIPC_0_IMS] Rx NS_IMSCC_RTP_TIMEOUT_IND (channel id=%d)
Line 358: [SIPC_1_IMS] Rx NS_IMSCC_RTCP_TIMEOUT_IND (channel id=%d)
Line 358: [SIPC_0_IMS] Rx NS_IMSCC_RTCP_TIMEOUT_IND (channel id=%d)
Line 373: [SIPC_1_IMS] Rx NS_IMSCC_IMS_ENGINE_RSP (result=0x%X)
Line 373: [SIPC_0_IMS] Rx NS_IMSCC_IMS_ENGINE_RSP (result=0x%X)
Line 396: [SIPC_1_IMS] Rx NS_IMSCC_FRAMETIME_GET_RSP (channel=%d, )
Line 396: [SIPC_0_IMS] Rx NS_IMSCC_FRAMETIME_GET_RSP (channel=%d, )
Line 411: [SIPC_1_IMS] Rx NS_IMSCC_FRAMETIME_NTF (operation=%d, channel=%d, RTPtime=%d, NTP_LS=%d, NTP_MS=%d)
Line 411: [SIPC_0_IMS] Rx NS_IMSCC_FRAMETIME_NTF (operation=%d, channel=%d, RTPtime=%d, NTP_LS=%d, NTP_MS=%d)
Line 426: [SIPC_1_IMS] Rx NS_IMSCC_OPTION_INFO_IND (Operation=%d, Channel id=%d, BitRate=%u, Event=%d, Volume=%d, Duration=%d, EndBit=%d)
Line 426: [SIPC_0_IMS] Rx NS_IMSCC_OPTION_INFO_IND (Operation=%d, Channel id=%d, BitRate=%u, Event=%d, Volume=%d, Duration=%d, EndBit=%d)
Line 442: [SIPC_1_IMS] Rx NS_IMSCC_TUNEAWAY_SET_RSP (Result=%d)
Line 442: [SIPC_0_IMS] Rx NS_IMSCC_TUNEAWAY_SET_RSP (Result=%d)
