Line 45: [SIPC_1_IMS] Tx NS_IMSCC_CHNL_GET_REQ
Line 45: [SIPC_0_IMS] Tx NS_IMSCC_CHNL_GET_REQ
Line 69: [SIPC_1_IMS] Tx NS_IMSCC_CHNL_SET_REQ (channel id=%d, operation=0x%X)
Line 69: [SIPC_0_IMS] Tx NS_IMSCC_CHNL_SET_REQ (channel id=%d, operation=0x%X)
Line 105: [SIPC_1_IMS] Tx NS_IMSCC_CHNL_READY_REQ (State=%d)
Line 105: [SIPC_0_IMS] Tx NS_IMSCC_CHNL_READY_REQ (State=%d)
Line 130: [SIPC_1_IMS] Tx NS_IMSCC_CODEC_GET_REQ (ReqType=0x%X, channel id=%d)
Line 130: [SIPC_0_IMS] Tx NS_IMSCC_CODEC_GET_REQ (ReqType=0x%X, channel id=%d)
Line 157: [SIPC_1_IMS] Tx NS_IMSCC_CODEC_SET_REQ (channel id=%d)
Line 157: [SIPC_0_IMS] Tx NS_IMSCC_CODEC_SET_REQ (channel id=%d)
Line 218: [SIPC_1_IMS] Tx NS_IMSCC_RTP_MEDIA_START_REQ (channel id=%d, status=0x%X, IPv6 enable=%d)
Line 218: [SIPC_0_IMS] Tx NS_IMSCC_RTP_MEDIA_START_REQ (channel id=%d, status=0x%X, IPv6 enable=%d)
Line 245: [SIPC_1_IMS] Tx NS_IMSCC_RTP_MEDIA_CHANGE_REQ (channel id=%d, status=0x%X)
Line 245: [SIPC_0_IMS] Tx NS_IMSCC_RTP_MEDIA_CHANGE_REQ (channel id=%d, status=0x%X)
Line 270: [SIPC_1_IMS] Tx NS_IMSCC_RTP_MEDIA_STOP_REQ (channel id=%d)
Line 270: [SIPC_0_IMS] Tx NS_IMSCC_RTP_MEDIA_STOP_REQ (channel id=%d)
Line 296: [SIPC_1_IMS] Tx NS_IMSCC_DTMF_SET_REQ (channel id=%d, payload type=%d, mode=0x%X)
Line 296: [SIPC_0_IMS] Tx NS_IMSCC_DTMF_SET_REQ (channel id=%d, payload type=%d, mode=0x%X)
Line 297: [SIPC_1_IMS] Clock Rate=0x%X, Rx payload type=0x%X
Line 297: [SIPC_0_IMS] Clock Rate=0x%X, Rx payload type=0x%X
Line 328: [SIPC_1_IMS] Tx NS_IMSCC_DTMF_REQ (channel id=%d, DTMF=%d)
Line 328: [SIPC_0_IMS] Tx NS_IMSCC_DTMF_REQ (channel id=%d, DTMF=%d)
Line 329: [SIPC_1_IMS] Cont Mode=%d, Cont Event=%d)
Line 329: [SIPC_0_IMS] Cont Mode=%d, Cont Event=%d)
Line 356: [SIPC_1_IMS] Tx NS_IMSCC_STAT_GET_REQ (channel id=%d)
Line 356: [SIPC_0_IMS] Tx NS_IMSCC_STAT_GET_REQ (channel id=%d)
Line 382: [SIPC_1_IMS] Tx NS_IMSCC_OPTION_SET_REQ (channel id=%d, option set=0x%X)
Line 382: [SIPC_0_IMS] Tx NS_IMSCC_OPTION_SET_REQ (channel id=%d, option set=0x%X)
Line 383: [SIPC_1_IMS] echo enable=%d
Line 383: [SIPC_0_IMS] echo enable=%d
Line 429: [SIPC_1_IMS] Tx NS_IMSCC_IMS_PDN_IP_SET_REQ (cid=%d, IP type=0x%X)
Line 429: [SIPC_0_IMS] Tx NS_IMSCC_IMS_PDN_IP_SET_REQ (cid=%d, IP type=0x%X)
Line 476: [SIPC_1_IMS] Tx NS_IMSCC_IMS_REGISTRATION_SET_REQ (status=%d, feature=%d, imsPsRatType=%d, volteErrCause=%d)
Line 476: [SIPC_0_IMS] Tx NS_IMSCC_IMS_REGISTRATION_SET_REQ (status=%d, feature=%d, imsPsRatType=%d, volteErrCause=%d)
Line 492: [SIPC_1_IMS] Tx NS_IMSCC_IMS_ENGINE_REQ (operation=0x%X)
Line 492: [SIPC_0_IMS] Tx NS_IMSCC_IMS_ENGINE_REQ (operation=0x%X)
Line 518: [SIPC_1_IMS] Tx NS_IMSCC_FRAMETIME_GET_REQ (operation=%d, channel id=%d)
Line 518: [SIPC_0_IMS] Tx NS_IMSCC_FRAMETIME_GET_REQ (operation=%d, channel id=%d)
Line 546: [SIPC_1_IMS] Tx NS_IMSCC_FRAMETIME_SET_REQ (operation=%d, channel id=%d)
Line 546: [SIPC_0_IMS] Tx NS_IMSCC_FRAMETIME_SET_REQ (operation=%d, channel id=%d)
Line 573: [SIPC_1_IMS] Tx NS_IMSCC_TUNEAWAY_SET_REQ (isEnabled=%d(0:Disabled, 1:Enabled))
Line 573: [SIPC_0_IMS] Tx NS_IMSCC_TUNEAWAY_SET_REQ (isEnabled=%d(0:Disabled, 1:Enabled))
