Line 43: [SIPC_1_SOUND] Rx NS_SOUND_CLOCK_NTF (status=0x%X)
Line 43: [SIPC_0_SOUND] Rx NS_SOUND_CLOCK_NTF (status=0x%X)
Line 58: [SIPC_1_SOUND] Rx NS_SOUND_WB_AMR_REPORT_NTF (WB AMR Report=0x%X)
Line 58: [SIPC_0_SOUND] Rx NS_SOUND_WB_AMR_REPORT_NTF (WB AMR Report=0x%X)
Line 68: [SIPC_1_SOUND] Rx NS_SOUND_AUDIO_DSP_NTF (initStatus=0x%X SuspendStatus=0x%X PcmOpenStatus=0x%X AboxStuckStatus=0x%X)
Line 68: [SIPC_0_SOUND] Rx NS_SOUND_AUDIO_DSP_NTF (initStatus=0x%X SuspendStatus=0x%X PcmOpenStatus=0x%X AboxStuckStatus=0x%X)
Line 84: [SIPC_1_SOUND] Rx NS_ULTRA_SONIC_INFO_NTF (UltraSonicInfo=%d(0:OFF, 1:ON))
Line 84: [SIPC_0_SOUND] Rx NS_ULTRA_SONIC_INFO_NTF (UltraSonicInfo=%d(0:OFF, 1:ON))
