Line 54: [SIPC_1_PHONE_BOOK] Invalid cmd type (main=0x%X, sub=0x%X, type=0x%X)
Line 54: [SIPC_0_PHONE_BOOK] Invalid cmd type (main=0x%X, sub=0x%X, type=0x%X)
Line 62: [SIPC_1_PHONE_BOOK] Undefined cmd (main=0x%X, sub=0x%X, type=0x%X)
Line 62: [SIPC_0_PHONE_BOOK] Undefined cmd (main=0x%X, sub=0x%X, type=0x%X)
Line 100: [SIPC_1_PHONE_NOOK] sipcSecCheckSimStatus failure
Line 100: [SIPC_0_PHONE_NOOK] sipcSecCheckSimStatus failure
Line 106: [SIPC_1_PHONE_BOOK] sipcPbCheckSimPbStatus() : PB initialization is failed
Line 106: [SIPC_0_PHONE_BOOK] sipcPbCheckSimPbStatus() : PB initialization is failed
Line 112: [SIPC_1_PHONE_BOOK] sipcPbCheckSimPbStatus() : PB is still initializing
Line 112: [SIPC_0_PHONE_BOOK] sipcPbCheckSimPbStatus() : PB is still initializing
Line 179: [SIPC_1_PHONE_BOOK] ucSubParamLen=%d
Line 179: [SIPC_0_PHONE_BOOK] ucSubParamLen=%d
Line 204: [SIPC_1_PHONE_BOOK] Tx Phone Book Access RSP (mode=0x%X, PB storage type=0x%X, index=%d, next index=%d)
Line 204: [SIPC_0_PHONE_BOOK] Tx Phone Book Access RSP (mode=0x%X, PB storage type=0x%X, index=%d, next index=%d)
Line 234: [SIPC_1_PHONE_BOOK] Tx Phone Book Access NTF (mode=0x%X, PB storage type=0x%X, index=%d)
Line 234: [SIPC_0_PHONE_BOOK] Tx Phone Book Access NTF (mode=0x%X, PB storage type=0x%X, index=%d)
Line 264: [SIPC_1_PHONE_BOOK] Tx Phone Book Storage RSP (PB storage type=0x%X, total count=%d, used count=%d)
Line 264: [SIPC_0_PHONE_BOOK] Tx Phone Book Storage RSP (PB storage type=0x%X, total count=%d, used count=%d)
Line 290: [SIPC_1_PHONE_BOOK] Tx Phone Book Storage List RSP (selected slot=0x%X, PB List=0x%04X)
Line 290: [SIPC_0_PHONE_BOOK] Tx Phone Book Storage List RSP (selected slot=0x%X, PB List=0x%04X)
Line 323: [SIPC_1_PHONE_BOOK] Tx Phone Book Entires Information RSP (PB storage type=0x%X, index min=%d, index max=%d, num max=%d, text max=%d)
Line 323: [SIPC_0_PHONE_BOOK] Tx Phone Book Entires Information RSP (PB storage type=0x%X, index min=%d, index max=%d, num max=%d, text max=%d)
Line 357: [SIPC_1_PHONE_BOOK] Tx 3G Phone Book Capability RSP (selected slot=0x%X, num of PB fields=%d)
Line 357: [SIPC_0_PHONE_BOOK] Tx 3G Phone Book Capability RSP (selected slot=0x%X, num of PB fields=%d)
Line 394: [SIPC_1_PHONE_BOOK] Tx 3G Phone Book Capability NTF (Selected slot=0x%X, Num of PB Fields=%d)
Line 394: [SIPC_0_PHONE_BOOK] Tx 3G Phone Book Capability NTF (Selected slot=0x%X, Num of PB Fields=%d)
Line 409: [SIPC_1_PHONE_BOOK] Rx Phone Book Access EXE (sipc msg len=%d, mode=0x%X, phonebook type=0x%X, index=%d)
Line 409: [SIPC_0_PHONE_BOOK] Rx Phone Book Access EXE (sipc msg len=%d, mode=0x%X, phonebook type=0x%X, index=%d)
Line 413: [SIPC_1_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 413: [SIPC_0_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 420: [SIPC_1_PHONE_BOOK] Invalid mode(=0x%X)
Line 420: [SIPC_0_PHONE_BOOK] Invalid mode(=0x%X)
Line 427: [SIPC_1_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 427: [SIPC_0_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 439: [SIPC_1_PHONE_BOOK] Phone Book Access was sent to stack
Line 439: [SIPC_0_PHONE_BOOK] Phone Book Access was sent to stack
Line 454: [SIPC_1_PHONE_BOOK] Rx Phone Book Access GET(Selected slot=0x%X, PB storage type=0x%X, Start Idx=%d, End Idx=%d)
Line 454: [SIPC_0_PHONE_BOOK] Rx Phone Book Access GET(Selected slot=0x%X, PB storage type=0x%X, Start Idx=%d, End Idx=%d)
Line 459: [SIPC_1_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 459: [SIPC_0_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 466: [SIPC_1_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 466: [SIPC_0_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 490: [SIPC_1_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 490: [SIPC_0_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 497: [SIPC_1_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 497: [SIPC_0_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 520: [SIPC_1_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 520: [SIPC_0_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 527: [SIPC_1_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 527: [SIPC_0_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 550: [SIPC_1_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 550: [SIPC_0_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 574: [SIPC_1_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 574: [SIPC_0_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 581: [SIPC_1_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 581: [SIPC_0_PHONE_BOOK] Invalid PB storage type(=0x%X)
Line 604: [SIPC_1_PHONE_BOOK] Invalid selected slot(=0x%X)
Line 604: [SIPC_0_PHONE_BOOK] Invalid selected slot(=0x%X)
