Line 203: [VHM]not defined codec type(%d)
Line 217: [VHM]StartMainVoiceLoop(%d)
Line 246: [VMM]Need to RxSe one more(dlyCnt:%d)
Line 349: [VHM]VoiceFwInit(amrMode:%d,Codec:%d,FSMode:%d,LBMode:%d)
Line 350: [VHM]VoiceFwInit(inPath:%d,Vol:%d)
Line 576: [VHM]Enc Start(%d) : codecMode(%d), evrcPktMode(%d), dtxSync(%d), dtxOpt(%d)
Line 644: [VHM]Dec Start(%d) : decFlag(%d),codecMode(%d),rxFrmType(%d),txFrmType(%d)
Line 761: [VHM]vhm_PreprocChCreation Start(%d)
Line 777: [VSS][vhm_CreateAboxChl] passInfo (0x%X) 
Line 782: [VSS][vhm_CreateAboxChl] VHM_sendSignalFromISR (0x%X) 
Line 793: [VHM]VoiceFWEnd Start(%d)
Line 850: [VHM]TXSE Start(%d)
Line 885: [VHM]VoiceLoop Start(%d)
Line 939: [VHM]RXSE Start(%d)
Line 1025: [VHM]not ready to proc DEC(%d,%d)
Line 1082: [VHM]EncDone(%d) : txFrmType(%d),vbrCodecMode(%d),sid(%d)
Line 1165: [VHM]EncDone : Undefined FRAME_SYNC_MODE(%d) !!!
Line 1197: [VHM]TXSE Done(%d)
Line 1246: [VHM]RXSE Done(%d)
Line 1289: [VHM]DecDone(%d) : evsCoreMode(%d)
Line 1295: [vhm_DecDoneEvt] decStatus (%d)
Line 1332: [vhm_DecDoneEvt] frmSyncMode (%d)
Line 1342: [vhm_DecDoneEvt] trigger RXSE PROC
Line 1359: vhm_SetSeParam: mismatch(%d,%d)
Line 1361: [VHM][EVT]SeParamSet(%d)
Line 1374: vhm_MuteTxVoice: mismatch(%d,%d)
Line 1376: [VHM][EVT]TxMute(%d)
Line 1395: vhm_MuteRxVoice : mismatch(%d,%d)
Line 1397: [VHM][EVT]RxMute(%d)
Line 1415: vhm_CtrlVolume: mismatch(%d,%d)
Line 1418: [VHM][EVT]VolumeCtrl(%d)
Line 1429: [VHM][EVT]AuxFuncCtrl(p:0x%d)
Line 1454: vhm_SetHwAudioPath: mismatch(%d,%d)
Line 1456: [EVT]vhm_SetHwAudioPath(%d)
