Line 293: [VSS][VHM_SetTaskTimeout]  timeout (0x%X)
Line 302: [VSS][VHM_SetTaskTimeout]  timeout (0x%X)
Line 432: [VSS][c2c_ipc_handler]: tid (0x%X) resID (%d) v3 (0x%X) 
Line 467: [VSS][c2c_event_handler] tid (0x%X) eventID (%d) resAddr (0x%X) p_msgq (0x%X) 
Line 531: [VSS][VHM_sendSignalFromISR] eventID (%d)  resAddr (0x%X) vss_interface().init (0x%X)
Line 545: [VSS][VHM_sendSignalFromISR] - c2c_vss_send_event - tid (0x%X) eventID (%d) vss_interface().init (0x%X)
Line 553: [VSS][VHM_sendSignalFromISR] - push_cpmsg - tid (0x%X) eventID (%d) resAddr (0x%X) vss_interface().init (0x%X)
Line 564: [VSS][VHM_sendSignalFromISR] eventID (%d)  resAddr (0x%X) vss_interface().init (0x%X)
Line 569: [VHM_sendSignalFromISR] - c2c_vss_send_ipc - eventID (0x%X) 
Line 594: [VSS][VHM_sendSignalFromTask] eventID (%d)  resAddr (0x%X) vss_interface().init (0x%X)
Line 608: [VSS][VHM_sendSignalFromTask] - c2c_vss_send_event - tid (0x%X) eventID (%d) vss_interface().init (0x%X)
Line 616: [VSS][VHM_sendSignalFromTask] - push_cpmsg - tid (0x%X) eventID (%d) resAddr (0x%X) vss_interface().init (0x%X)
Line 627: [VSS][VHM_sendSignalFromTask] eventID (%d)  resAddr (0x%X) vss_interface().init (0x%X)
Line 633: [VSS][VHM_sendSignalFromTask] - c2c_vss_send_ipc - eventID (0x%X) 
Line 658: [VSS][VHM_sendSignalFromRES] resID (%d) 
Line 679: [VSS][VHM_CreateCPmainthread] Failed to create a thread
Line 686: [VSS][VHM_CreateCPmainthread] tid (0x%X) 
Line 701: [VSS][VHM_CreateCPsubthread] Failed to create a thread
Line 708: [VSS][VHM_CreateCPSubthread] tid (0x%X) 
Line 722: [VSS][VHM_CreateCPstatethread] Failed to create a thread
Line 729: [VSS][VHM_CreateCPstatethread] tid (0x%X) 
Line 768: [VSS][InitVHMMemory] CP_Test_Mode (%d) CP_Test_IO (%d) CP_Test_Sampling(%d)
Line 873: [VSS][VHM_Init_Main] Entry : ABoxState(%d) 
Line 874: [VSS][VHM_Init_Main] g_Core_use_case(0x%X) g_Core_map(0x%X) g_Core_dualmap(0x%X) 
Line 978: [VSS][VHM_Init_Main] - Done 
Line 986: [VHM_initialize] VHM_Init_Sub_Entry
Line 1010: [VHM_initialize] VHM_Init_Sub_Thread_Done
Line 1038: [CPstateThread] CPstateThread was started
Line 1062: [VSS][CP_EVENT_VHM_FW_INIT_res] resID (%d) dump_cnt (%d)
Line 1066: [VSS][CP_EVENT_VHM_FW_INIT_res] resID (%d) core_0(%d) core_1(%d) 
Line 1077: [VSS][CP_EVENT_VHM_CH_Create_res] resID (%d) dump_cnt (%d)
Line 1084: [VSS][CP_EVENT_VHM_FW_INIT_res] resID (%d) core_0(%d) core_1(%d)  
Line 1096: [VSS][CP_EVENT_VHM_CH_Destroy_res] resID (%d) dump_cnt (%d)
Line 1103: [VSS][CP_EVENT_VHM_CH_Destroy_res] resID (%d) core_0(%d) core_1(%d)  
Line 1114: [VSS][CP_EVENT_VHM_Voc_Tx_Exe_res] resID (%d) dump_cnt (%d)
Line 1127: [VSS][CP_EVENT_VHM_Voc_Rx_Exe_res] resID (%d) dump_cnt (%d)
Line 1141: [VSS][CP_EVENT_VHM_SE_Tx_Exe_res] resID (%d) dump_cnt (%d)
Line 1154: [VSS][CP_EVENT_VHM_SE_Rx_Exe_res] resID (%d) dump_cnt (%d)
Line 1167: [VSS][CP_EVENT_VHM_HeartBeat_res] resID (%d) dump_cnt (%d)
Line 1200: [CPmainThread] Received a unknown msg (%d:%d) (%d)
Line 1223: [VSS][CP_EVENT_VHM_Voc_Tx_Exe] dump_cnt (%d)
Line 1244: [CPmainThread] CPmainThread was started
Line 1277: [VSS][CP_EVENT_VHM_Create] eventID (%d) 
Line 1285: [VSS][CP_EVENT_VHM_CH_Create] eventID (%d) 
Line 1293: [VSS][VHM_sendSignalFromISR] - c2c_vss_send_event - tid (0x%X)  eventID (%d) resAddr (0x%X) taskevent (0x%X) vss_interface().init (0x%X)
Line 1303: [VSS][CP_EVENT_VHM_CH_Create_Tx] eventID (%d) 
Line 1311: [VSS][CP_EVENT_VHM_CH_Destroy] eventID (%d) 
Line 1319: [VSS][CP_EVENT_VHM_CH_Destroy] eventID (%d) 
Line 1329: [VSS][VHM_sendSignalFromISR] - c2c_vss_send_event - tid (0x%X)  eventID (%d) resAddr (0x%X) taskevent (0x%X) vss_interface().init (0x%X)
Line 1340: [VSS][CP_EVENT_VHM_CH_Destroy_Tx] eventID (%d) 
Line 1347: [VSS][CP_EVENT_VHM_VIFStop_forced] eventID (%d) 
Line 1361: [VSS][CP_EVENT_VHM_Voc_Rx_Exe] eventID (%d) dump_cnt (%d)
Line 1369: [VSS][VHM_MAINLOOP_START] eventID (%d) dump_cnt (%d)
Line 1378: [VSS][VHM_DLVOICE_START] eventID (%d) dump_cnt (%d)
Line 1390: [VSS][CP_EVENT_VHM_SE_Tx_Exe] eventID (%d) dump_cnt (%d)
Line 1401: [VSS][CP_EVENT_VHM_SE_Rx_Exe] eventID (%d) dump_cnt (%d)
Line 1412: [VSS][CP_EVENT_VHM_SE_SetParam] eventID (%d) dump_cnt (%d)
Line 1422: [VSS][CP_EVENT_VHM_SE_TxMute] eventID (%d) dump_cnt (%d)
Line 1432: [VSS][CP_EVENT_VHM_SE_RxMute] eventID (%d) dump_cnt (%d)
Line 1445: [VSS][CP_EVENT_VHM_SE_RxVol] eventID (%d) dump_cnt (%d)
Line 1457: [VSS][CP_EVENT_VHM_SE_AuxFunc] eventID (%d) dump_cnt (%d)
Line 1468: [VSS][CP_EVENT_VHM_cpAudioPath] eventID (%d) dump_cnt (%d)
Line 1482: [VSS][CP_EVENT_VHM_EstablishCall] eventID (%d) dump_cnt (%d)
Line 1489: [VSS][CP_EVENT_VHM_ReleaseCall] eventID (%d) dump_cnt (%d)
Line 1508: [CPmainThread] CP_EVENT_VHM_CallRecTimerTrig Received from ISR_Timer20ms
Line 1513: [CPmainThread] CP_EVENT_VHM_CallRecPcmcTrig Received from Pcmc
Line 1578: [VSS][CPmainThread] Received a unknown msg (%d:%d) (0x%x)
