Line 171: [EXP] DRX Working.. wait(%d)
Line 321: [EXP] SetTestSimStatus (%d)
Line 591: [EXP] gL1DsdsHoldL2 (%d -> %d)
Line 775: [EXP] HALEXP_UpdateRxModeTime(%d): Acc(%d) Cur(%d)
Line 791: [EXP] HALEXP_UpdateRxModeTime(%d): Acc(%d) Cur(%d, %d, %d) (TdpState:%d RAT:%d) 
Line 816: [EXP] HALEXP_GetAndClearRxModeTime (%d)(TdpState:%d RAT:%d)
Line 843: [EXP] HALEXP_GetAndClearTxModeTime ( %d  %d  %d  %d  %d )
