Line 128:  NORMAL Initialisation of <GmmCellIndicationt> 
Line 166:  GSM to UMTS Initialisation of <GmmCellIndicationt> 
Line 172:  UMTS to GSM Initialisation of <GmmCellIndicationt> 
Line 178:  Unknown Initialisation Type (%x) in mm_InitGmmCellIndication 
Line 209: UMTS Moved from No PS service to In PS serviec
Line 224: UMTS Current and Sim RAI are same ChangeinRai : False
Line 228: UMTS Current and Sim RAI are different ChangeinRai : TRUE
Line 330: CnCommonNasInfo Absent !!!! PLMN Changed without LAC changing?! Msg ignored in  mm_UpdateAndProcessGmmCellData 
Line 364: SIB derived CN information does not include PS domain specific SI (i.e. RAC and network mode)...assuming PS domain currently unavailable in selected cell
Line 377: Network sourced CN information does not include PS domain specific SI (i.e. RAC and network mode)...assuming PS domain currently unavailable in selected cell
Line 434: PLMN identity not included - using previously stored value
Line 459: CN Common SI (LAC) not included - using previously stored value
Line 464: SIB derived CN information does not include CN common GSM-MAP NAS SI (i.e. LAC)...
Line 488: PLMN identity not included - using previously stored value
Line 511: CN Common SI (LAC) not included - using previously stored value
Line 550:  Setting GMM_RAI_CHANGED_FLG_...
Line 617:  URRC_MM_NO_CELL_IND....
Line 654: Moved from PS no service to PS in Service
Line 661: GSM Current and Sim RAI are same ChangeinRai : False
Line 665: GSM Current and Sim RAI are different ChangeinRai : TRUE
Line 694: mm_GmmCellData.CellChange is set to FALSE.
Line 699: mm_GmmCellData.CellChange is set to TRUE.
Line 720: NwExtUtbf= %d
Line 751: EncodedSizeinBits -> %d 
Line 752: Access Technology changed...
Line 756: Access Technology did not change...
Line 774:  CR 98 :Set : mm_SetGmmFlag....
Line 780:  CR 98 :Clear : mm_SetGmmFlag....
Line 814:  ....cell does not support PS.
Line 819: ....ignored as DataResumption == GRR_GMM_NO_RESUMPTION.
Line 837:  GRR_MM_NO_CELL_IND....
Line 863: Because of Power off detach or PS detach PS off and  GMM Deregistered we skip GmmCellData process.
Line 914:  ERROR: unknown TypMsg 0x%02X in MM_UMTS_RAT_MODE 
Line 959:  ERROR: unknown TypMsg 0x%X in MM_GSM_RAT_MODE 
Line 982: discard GMM SM EST REQ
Line 1010: SameRrConnexFailAction = %d, ProcessCellInfo =%d 
Line 1037: Current serving cell is not supportting PS services(or barred), GMM_GPRS_ATTACH_FLG = FALSE
Line 1041: LAI is not changed, so send Registration ind to NS for PS barred status
Line 1046: NO CELL IND, keep GMM_GPRS_ATTACH_FLG == TRUE
Line 1052: Current serving cell is supporting PS services and UE GMM REG/UPDATED, GMM_GPRS_ATTACH_FLG = TRUE
Line 1056: Send reg status ind(PS not supported -> supported) on recovery to prev reg RAI
Line 1108: GMM shall process new cell details now...
Line 1113: GMM shall process new Unit Data Ind details now...
Line 1120: NMO-1 GMM shall process new cell details now. Received GSM CELL IND ..
Line 1139: GMM shall not process new cell details now...shall process on completion of MM location updating procedure
Line 1151: GMM shall not process new cell details...CSFB call about to initiated
Line 1159: In MM_WAIT_FOR_RR_CON_LOC_UPD state LAI changed, After Cell indication LAU should be initiated..GMM shall not process new cell details now till Perform LAU procedure
Line 1174: GMM shall not process new cell details...URRC_MM_CELL_IND received in while a PS signalling connection exists
Line 1181: GMM shall process new cell details now...
Line 1207: GMM processing of new cell details in %s in mm_ProcessGmmCellInformation
Line 1268: Attempting to go back to GMM State before Supension...mm_GmmStateBeforeSuspension = %s
Line 1274: Abort any ongoing GMM procedure and later Trigger  GPRS detach procedure in GMM state= %s
Line 1319: GMM state was GMM_SERVICE_REQUEST_INITIATED but have moved to GSM RAT, reverting to GMM_REGISTERED
Line 1369: ERROR: Invalid mm_GmmState....
Line 1436: CLEARING Gmm Regist status Cause
Line 1441: NOT CLEARING Gmm Regist status Cause, Cause %d
Line 1548:  Need to do GPRS Attach UE is in NMO1 So try Combined Attach to establish the Gs association in the MSC/VLR.
Line 1556: GMM is in LIMITED and PS domain barred... So nothing done here... 
Line 1572: RAI Changed
Line 1588: Cell Changed & Must Retry in New Cell
Line 1595: GMM_T3302 had expired while GMM was suspended
Line 1608: Cell changed and Att req action is GMM_NO_ATT_ACTION under attemping to attach / dereg state, need to do attach again.
Line 1658: GMM_NO_IMSI -> Should Never Have Got Here !!! 
Line 1666: ERROR: Unexpected mm_GmmServiceState....
Line 1678: GPRS attach (re)initiation...
Line 1707: CS call had been attempted, retry now...
Line 1761: Change of Cell into New Routing Area....
Line 1772: New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
Line 1788: GPRS Attach Procedure Following Intersystem Change Between Cells Belonging to the Same RA....
Line 1804: Change of cell within the same RA => Perform Cell Update [24.008]-4.7.3.1.5.e....
Line 1819: Access barred Due to Access Class Control....
Line 1831: Must Break RR Con. .
Line 1844: Lower Layer Failure....
Line 1862: Loss of coverage during Signalling, end the signalling
Line 1933: GMM_REGISTERED.mm_GmmCellData.NetworkService = %d 
Line 1968: ISR is activated but RAI is changed after L2U Rat Change. RRC Est Cause is set to InterRAT Cell Reselection.
Line 1997: RAU recovery procedure is performed..
Line 2030: RAU recovery procedure is performed..
Line 2041: RAT Change to UMTS Detected -> GSM to UMTS Intersystem Change Between Cells Belonging to Same RA...GPRS Functional State was %s on Intersystem Change....
Line 2046:  => Initiate RAU Procedure Immediately....
Line 2058: Normal RAU Procedure on Intersystem Handover from GSM to UMTS during CS Connection....
Line 2067: RAU Procedure Not Required Until Uplink Signalling or Data Transmission. [24.008]-4.7.1.7 (b)...
Line 2074: RAT Change to GSM Failed, Now Back in UMTS again -> MS in Same Access Network as when last sent user data or signalling, normal procedures shall be followed.....
Line 2095: mm_RauForGprsResumeReEntryFlag is RESET as RauNeeded is Set....
Line 2108: RAU Procedure Initiation Required for GPRS Resumption in the Network....DataResumption=%d, mm_RauForGprsResumeReEntryFlag=%d
Line 2120: RAU Procedure Initiation as GMM_T3302 Expired in GMM_SUSPENDED state....
Line 2129: RAU recovery procedure is performed..
Line 2139: Cell update procedure will be blocked during Manual PLMN searching.
Line 2146: Change of Cell in Same Routing Area....
Line 2162: RAT Change to GSM Detected -> UMTS to GSM Intersystem Change Between Cells Belonging to Same RA....PMM functional state was %s on intersystem change....
Line 2167:  => Initiate RAU Procedure Immediately....
Line 2175: RAU procedure not required until uplink signalling or data transmission. [24.008]-4.7.1.7 (b)...
Line 2195:  => Initiate RAU Procedure due to MM_AUTO_PLACEMENT_IN_QUEUE....
Line 2204: RAT Change to UMTS Failed, Now Back in GSM again -> MS in same access network as when last sent user data or signalling, normal procedures shall be followed.....
Line 2262: change of cell into new routing area....
Line 2281: change of cell in same routing area having received cause 'Retry upon entry into a new cell'....
Line 2300: GMM CELL DATA RAI != SIM RAI and No timer for retrying RAU, Here RAU is necessary. 
Line 2308: RAU procedure as GMM_T3302 expired in GMM_SUSPENDED state...
Line 2321: RAU procedure should be triggered due to NMO change (not periodic)
Line 2369: change of cell into new routing area....
Line 2380: RAU needed flag is set
Line 2418: access no longer barred....
Line 2471: Change of Cell into New Routing Area....
Line 2486: Network mode change during GPRS detach procedure for CS services
Line 2503: IMSI Detach Procedure After RAU Procedure Following Intersystem Change Between Cells Belonging to the Same RA....
Line 2517: Change of Cell in Same Routing Area....
Line 2529: Lower Layer Failure....
Line 2614:  ERROR: mm_GmmState and mm_GmmServiceState incompatible! 
Line 2629: MO/MT Call was attempted in NMO1. This should be stopped before RAU Procedure ....
Line 2658: RAU will be pended while MO/MT call is in progress....
Line 2676: Initiating RAU Procedure .... after WFRAU timer is expired
Line 2684: Initiating RAU Procedure .... if Quick Rollback is over
Line 2691:  Quick rollback is in progress, so processing MM cell ind further, if QRB for G2L is failed 
Line 2697: Initiating RAU Procedure ....
Line 2714: RAU procedure not initiated due to access class barred....
Line 2731: SM Informed of 'Lost' Radio Coverage....
Line 2736: SM Informed of Regained Radio Coverage....
Line 2777: SM Informed of 'Lost' Radio Coverage....
Line 2783: SM Informed of Regained Radio Coverage....
Line 2789: Resumed Again on UMTS Rat So no need to Do Anything 
Line 2827: CS call had been attempted, retry now...
Line 2860: CS call had been attempted, retry now...
Line 2910: Change of Cell into New Routing Area. Starting RAU...
Line 2919: New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
Line 2942: RAT Change Detected During RAU Procedure...RAU Procedure Following Intersystem Change Between Cells Belonging to the Same RA
Line 2956: Change of Cell in Same Routing Area....
Line 2968: Access Barred Due to Access Class Control....
Line 2980: Must Break RR Con. .
Line 3005: Gmm cell data. network service exceeds the limit
Line 3029: SM informed of 'Lost' Radio Coverage....
Line 3068: Change of Cell into New Routing Area....
Line 3076: Change of RAC Detected, during Detach for PS Switching
Line 3120: New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
Line 3141: RAT Change Detected During Detach -> RAU Procedure then Normal GPRS Detach Following Intersystem Change Between Cells Belonging to the Same RA....
Line 3163: change of cell within the same RA....
Line 3208: .... lower layer failure
Line 3244: Change of cell into new RA...
Line 3278: RRC requested to 'release' PS signalling connection before RAU procedure initiation...
Line 3288: PMM_CONNECTED: RRC requested to 'release' PS signalling connection before RAU procedure initiation...%d
Line 3295: RAU procedure 'interupts' service request procedure...
Line 3358: CS call had been attempted, retry now...
Line 3377: Loss of coverage during service request procedure...
Line 3390: mm_GmmCellIndDb[MmStackId].mm_GmmCellData.NetworkService exceeds the limit
Line 3399: SM informed of 'lost' radio coverage....
Line 3416: RRC requested to 'release' PS signalling connection Because Lost Coverage Before Moving to Conn Mode
Line 3456: GCF Mode is Enabled
Line 3459: In UMTS RAT, PMM connected Mode and Network mode 1
Line 3463: Current and SIM data PLMNs are not same and PLMN Found in Equivalent Plmn List
Line 3466: LA and RA of the SIM and the current cell data are same.
Line 3635: GRR_GMM_SUSPEND_IND received in state %s 
Line 3679: mm_EncodedDrxParam = 0x%02X 0x%02X
Line 3844:  Invalid NewState in mm_SetGmmStateBeforeSuspension 
Line 4120:  Re-setting GMM CellData 
Line 4140:  Setting GMM CellData for Recovery 
Line 4159:  Restore Gmm CellData for Recovery 
Line 4189:  GMM Cell Data RAC -> 0x%02X 
Line 4201: mm_GmmCellData.Rai                 = %02X %02X %02X %02X %02X %02X 
Line 4220: mm_GmmCellData.NetworkMode         = %s
Line 4233: ---------------------Current GMM cell details---------------------
Line 4235:  RAT mode -> %s
Line 4240:  Access tech type -> %s
Line 4244:  RAT mode -> %s,          Network service -> %s
Line 4249:  Forbidden PLMN
Line 4255:  Forbidden PLMN for GPRS services
Line 4261:  Forbidden LA
Line 4267:  Forbidden LA for roaming
Line 4273:  PLMN selection has been started by MM
Line 4277:  Network access -> %s,         Network mode -> %s 
Line 4280:  RAI -> %02X %02X %02X %02X %02X %02X,          Cell identity -> %07X
Line 4288: Cell change -> %s, Data resumption -> %s
Line 4293:  Cell change -> %s
Line 4307: ---------------------Previous GMM cell details---------------------
Line 4309:  RAT mode -> %s,          Network mode -> %s
Line 4314:  Access tech type -> %s
Line 4318:  RAI -> %02X %02X %02X %02X %02X %02X,          Cell identity -> %07X
Line 4387: Even though Band is changed in NMO1, we don't have anything to send again! 
Line 4431: Wrong Action =%d 
