Line 375: [SYSTEM] InitSystemTime: RTG offset(%d)
Line 553: [SYSTEM] SetDlSystemInfo(RX%d RF%d): sys_info(%08x -> %08x)
Line 673: [SYSTEM] SetDrxMode(RX%d): mode(%d)
Line 709: [SYSTEM] SetDrxStartPos: mode(%d), time(0x%x), drx_counter(0x%x), SFN(%d), TTI(%d), Offset(%d)
Line 774: [SYSTEM] SetIratTriggerSignal: enable(%d), time(%08x), len(%d)
Line 866: [SYSTEM] SetRtgLoad(RTG%d, RFD_RTG%d): RTG(%x %x) diff(%d)
Line 878: [SYSTEM] SetRtgLoad(RTG%d, RFD_RTG%d): offset(%d)
Line 1078: [SYSTEM] ConfigRtg(DEBUG): rtg_counter(%d), gen_counter(%d), general_snap(%d), cur_sfn(%d)
Line 1093: [SYSTEM] ConfigRtg(RTG%d): offset(%d), copy(%x), bw(%d), diff(%d), rtg(%d -> %d)
Line 1315: [SYSTEM] RTG%d: bw(%d), diff(%d), rtg(%d -> %d)
Line 1338: [SYSTEM] AlignRtg(RTG%d)
Line 1431: [SYSTEM] CopyRtg(%d)(RTG%d -> RTG%d)[shift %d]
Line 1483: [SYSTEM] SetSfn(RTG%d) (RFD%d): sfn(%d)
Line 1821: [SYSTEM] EnableSysTimeIntr(%d): mode(0x%x), time(0x%x)
Line 1905: [SYSTEM] CheckSysTimeCommonIntr: en(0x%08x), pend(0x%08x)
Line 2132: [SYSTEM] SetGapMode(CC%d): mode(%d), bw(%d), length(%d), sfn_tti(%d), offset(%d,%d)
Line 2221: [SYSTEM] SetCaMode(CC%d): on(%d), time(%d)
Line 2323: [SYSTEM] SetAgcAntSel(RF%d): rtg(%d)
Line 2382: [SYSTEM] SetTrxSwitch(RF%d): rtg(%d), sys_info(%08x) dlul_BB(%08x) uldl_BB(%08x) dlul_RFD(%08x) uldl_RFD(%08x)
Line 2558: [SYSTEM] HAL_CheckCcGroupingInfo(0x%x): RTG0(%d), RTG1(%d), RTG2(%d), RTG3(%d), RTG4(%d), RTG5(%d)
Line 2559: [SYSTEM] HAL_CheckCcGroupingInfo(0x%x): RTG6(%d), RTG7(%d) 
Line 2560: [SYSTEM] HAL_CheckCcGroupingInfo : CC0(%d), CC1(%d), CC2(%d), CC3(%d), CC4(%d), CC5(%d)
Line 2561: [SYSTEM] HAL_CheckCcGroupingInfo : CC6(%d), CC6(%d)
Line 2587: [RXF] SetTrxOverrideMode(%d):(0x%08x)
Line 2629: [RXF] SetTrxOverrideMode(%d): rf(%d), TRX_CFG_ON(0x%08x), TRX_CFG_OFF(0x%08x)
