Line 197: [HALRXF] SetMaxAnaDifPathNum: Digital Path(%d), Analog Path(%d)
Line 216: [HALRXF] %s: Wrong %s(%d)
Line 217: [HALRXF] %s: Wrong %s(%d)
Line 218: [HALRXF] %s: Wrong %s(%d)
Line 241: [HALRXF] SwapIQ: rat(%d), dcr(%d), enable(%d)
Line 269: [HALRXF] %s: Wrong %s(%d)
Line 284: [HALRXF] %s: Wrong %s(%d)
Line 697: [HALRXF] %s: Wrong %s(%d)
Line 698: [HALRXF] %s: Wrong %s(%d)
Line 815: [HALRXF] InitRxFilter: Worng Rat(%d)
Line 825: [HALRXF] InitRxFilter: mode(%d)
Line 853: [HALRXF] %s: Wrong %s(%d)
Line 854: [HALRXF] %s: Wrong %s(%d)
Line 855: [HALRXF] %s: Wrong %s(%d)
Line 906: [HALRXF] %s: Wrong %s(%d)
Line 967: [HALRXF] ConfigDvga: Worng Rat(%d)
Line 978: [HALRXF] ConfigDvga: rat(%d), mxr_sel(%d), enable(%d), bw(%d)
Line 1005: [HALRXF] %s: Wrong %s(%d)
Line 1006: [HALRXF] %s: Wrong %s(%d)
Line 1007: [HALRXF] %s: Wrong %s(%d)
Line 1038: [HALRXF] ConfigSrrcf: rat(%d), mxr_sel(%d), enable(%d)
Line 1059: [HALRXF] %s: Wrong %s(%d)
Line 1060: [HALRXF] %s: Wrong %s(%d)
Line 1087: [HALRXF] ConfigIQC[DISABLE]: Worng Rat(%d)
Line 1097: [HALRXF] ConfigIQC[DISABLE]: rat(%d), iqc_sel(%d)
Line 1118: [HALRXF] %s: Wrong %s(%d)
Line 1119: [HALRXF] %s: Wrong %s(%d)
Line 1155: [HALRXF] ConfigIQC[INIT]: Worng Rat(%d)
Line 1165: [HALRXF] ConfigIQC[INIT]: rat(%d), iqc_sel(%d)
Line 1186: [HALRXF] %s: Wrong %s(%d)
Line 1187: [HALRXF] %s: Wrong %s(%d)
Line 1227: [HALRXF] ConfigIQC[ENABLE]: Worng Rat(%d)
Line 1237: [HALRXF] ConfigIQC[ENABLE]: rat(%d), iqc_sel(%d)
Line 1258: [HALRXF] %s: Wrong %s(%d)
Line 1259: [HALRXF] %s: Wrong %s(%d)
Line 1280: [HALRXF] ConfigIQC[OVR]: Worng Rat(%d)
Line 1290: [HALRXF] ConfigIQC[ENABLE]: rat(%d), iqc_sel(%d)
Line 1311: [HALRXF] %s: Wrong %s(%d)
Line 1312: [HALRXF] %s: Wrong %s(%d)
Line 1335: [HALRXF] ConfigIQC[RESET]: Worng Rat(%d)
Line 1345: [HALRXF] ConfigIQC[ENABLE]: rat(%d), iqc_sel(%d)
Line 1366: [HALRXF] %s: Wrong %s(%d)
Line 1367: [HALRXF] %s: Wrong %s(%d)
Line 1407: [HALRXF] ConfigDCR[DISABLE]: Worng Rat(%d)
Line 1417: [HALRXF] ConfigDCR[DISABLE]: rat(%d), dcr_sel(%d)
Line 1438: [HALRXF] %s: Wrong %s(%d)
Line 1439: [HALRXF] %s: Wrong %s(%d)
Line 1487: [HALRXF] %s: Wrong %s(%d)
Line 1488: [HALRXF] %s: Wrong %s(%d)
Line 1560: [HALRXF] ConfigDCR[INIT]: Worng Rat(%d)
Line 1570: [HALRXF] ConfigDCR[INIT]: rat(%d), dcr_sel(%d)
Line 1591: [HALRXF] %s: Wrong %s(%d)
Line 1592: [HALRXF] %s: Wrong %s(%d)
Line 1650: [HALRXF] ConfigDCR[ENABLE]: Worng Rat(%d)
Line 1660: [HALRXF] ConfigDCR[ENABLE]: rat(%d), dcr_sel(%d)
Line 1681: [HALRXF] %s: Wrong %s(%d)
Line 1682: [HALRXF] %s: Wrong %s(%d)
Line 1730: [HALRXF] ConfigDCR[OVR]: Worng Rat(%d)
Line 1740: [HALRXF] ConfigDCR[OVR]: rat(%d), dcr_sel(%d)
Line 1761: [HALRXF] %s: Wrong %s(%d)
Line 1762: [HALRXF] %s: Wrong %s(%d)
Line 1817: [HALRXF] ConfigDCR[RESET]: Worng Rat(%d)
Line 1827: [HALRXF] ConfigDCR[RESET]: rat(%d), dcr_sel(%d)
Line 1850: [HALRXF] %s: Wrong %s(%d)
Line 1851: [HALRXF] %s: Wrong %s(%d)
Line 1852: [HALRXF] %s: Wrong %s(%d)
Line 1907: [HALRXF] %s: Wrong %s(%d)
Line 1908: [HALRXF] %s: Wrong %s(%d)
Line 1965: [HALRXF] ConfigAGC[INIT]: Worng Rat(%d)
Line 1975: [HALRXF] ConfigAGC[INIT]: rat(%d), mxr_sel(%d), dcr_sel(%d)
Line 1996: [HALRXF] %s: Wrong %s(%d)
Line 1997: [HALRXF] %s: Wrong %s(%d)
Line 2035: [HALRXF] ConfigAGC[OV]: Worng Rat(%d)
Line 2045: [HALRXF] ConfigAGC[OV]: rat(%d), mxr_sel(%d)
Line 2069: [HALRXF] %s: Wrong %s(%d)
Line 2070: [HALRXF] %s: Wrong %s(%d)
Line 2107: [HALRXF] ConfigAGC[RESET]: Worng Rat(%d)
Line 2117: [HALRXF] ConfigAGC[RESET]: rat(%d), mxr_sel(%d)
Line 2180: [HALRXF] %s: Wrong %s(%d)
Line 2181: [HALRXF] %s: Wrong %s(%d)
Line 2186: [HALRXF] SetPgcRamTable: RXF_PGC_MODE(0x%X)
Line 2231: [HALRXF] SetPgcRamTable: Worng Rat(%d)
Line 2264: [HALRXF] SetPgcRamTable: RAM%d[%d] = WR(0x%x, 0x%x), RD(0x%x, 0x%x)
Line 2280: [HALRXF] SetPgcRamTable: pgc(%d), band(%d -> %d), ram(%d, %d), size(%d)
Line 2317: [HALRXF] %s: Wrong %s(%d)
Line 2318: [HALRXF] %s: Wrong %s(%d)
Line 2319: [HALRXF] %s: Wrong %s(%d)
Line 2353: [HALRXF] SetPgcRamSel: dcr(%d), pgc(%d), Pgc_ram_sel(%d, %d)
Line 2388: [HALRXF] %s: Wrong %s(%d)
Line 2389: [HALRXF] %s: Wrong %s(%d)
Line 2436: [HALRXF] %s: Wrong %s(%d)
Line 2462: [HALRXF] SetAgcHys: Worng Rat(%d)
Line 2472: [HALRXF] SetAgcHys: mxr(%d), enable(%d)
Line 2507: [HALRXF] %s: Wrong %s(%d)
Line 2508: [HALRXF] %s: Wrong %s(%d)
Line 2509: [HALRXF] %s: Wrong %s(%d)
Line 2510: [HALRXF] %s: Wrong %s(%d)
Line 2558: [HALRXF] %s: Wrong %s(%d)
Line 2559: [HALRXF] %s: Wrong %s(%d)
Line 2671: [HALRXF] SetRxFilterMxr: Worng Rat(%d)
Line 2681: [HALRXF] SetRxFilterMxr: rf(%d), dcr(%d), mxr(%d), mode(%x), bw(%d) mixer_next(%8x)
Line 2710: [HALRXF] %s: Wrong %s(%d)
Line 2733: [HALRXF] SetInterpolator: Worng Rat(%d)
Line 2772: [HALRXF] %s: Wrong %s(%d)
Line 2818: [HALRXF] %s: Wrong %s(%d)
Line 2819: [HALRXF] %s: Wrong %s(%d)
Line 2925: [HALRXF] SetFbRx: fbDumpA(%X), fbDumpAccL(%X), fbAccL1(%X), fbAccL2(%X)
Line 2991: [HALRXF] SetInterpolator: Worng Rat(%d)
Line 3001: [HALRXF] SetFbRx: enable(%d), rf(%d), dcr(%d), mode(%x), bw(%d)
Line 3072: [HALRXF] %s: Wrong %s(%d)
Line 3073: [HALRXF] %s: Wrong %s(%d)
Line 3104: [HALRXF] %s: Wrong %s(%d)
Line 3105: [HALRXF] %s: Wrong %s(%d)
Line 3178: [HALRXF] SetDvgaHys: Worng Rat(%d)
Line 3188: [HALRXF] SetDvgaHys: enable(%d), hys(%d, %d, %d, %d, %d)
Line 3215: [HALRXF] %s: Wrong %s(%d)
Line 3230: [HALRXF] SetDif: dif(0x%X)
Line 3260: [HALRXF] %s: Wrong %s(%d)
Line 3272: [HALRXF] SetModeSetChange bw(%d) dcr_sel(%d) dvalid_sel(0x%X) feedbase_sel(0x%X:0x%X)
Line 3284: [HALRXF]  SetModeSetChange feedbackread(0x%X)
Line 3311: [HALRXF] SetModeSetChange feedbackread(0x%X)
Line 3319: [HALRXF] SetModeSetChange dcr_sel(%d), ratsamplingchanged(%d)
Line 3348: [4G_DRDS] SetAgcAntInputForEdvSpecialCase : RXF_AGC_ANT_INPUT_AVG_SEL , input (%x)
Line 3362: [4G_DRDS] SetAgcAntInputForEdvSpecialCase : RXF_GAIN_AVG_INPUT , input (%x)
Line 3376: [4G_DRDS] SetAgcAntInputForEdvSpecialCase : RXF_AGC_ANT_INPUT , input (%x)
Line 3387: [RXF] SetAgcAntInputForEdvSpecialCase: avg_sel(%08x) avg_input(%08x, %08x) input(%08x, %08x)
Line 3431: [RXF] ConfigGainSplitter: mode(%x), dcr(%d), reg32data(%x)
