Line 83: rachResourcesController==NULL
Line 135: tphy_CRachResources instance mem allocation failed
Line 321: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->pccpchInfo.cellParamId out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 325: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->pccpchTxPower out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 330: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.SyncULInfo.SyncULCodeBitmap out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 335: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.SyncULInfo.PRXUpPCHdes out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 340: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.SyncULInfo.powerRampupStep out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 345: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.SyncULInfo.MaxSyncULTransmissions out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 350: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.SyncULInfo.mmax out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 355: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.SyncULInfo.ERUCCH_SyncUL_Code out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 360: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.prachFpachCount out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 371: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].MidambleShiftandBurst.MidambleAllocationMode out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 376: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].MidambleShiftandBurst.MidambleConfiguration out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 381: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].MidambleShiftandBurst.MidambleShift out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 386: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].TimeSlot out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 393: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].ChannelisationCodeList[m] out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 399: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].FPACHInfo.MidambleShiftandBurst.MidambleAllocationMode out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 404: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].FPACHInfo.MidambleShiftandBurst.MidambleConfiguration out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 409: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].FPACHInfo.MidambleShiftandBurst.MidambleShift out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 414: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].FPACHInfo.TimeSlot out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 419: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].FPACHInfo.ChannelisationCode out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 424: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.PrachFpach[n - 1].FPACHInfo.WT out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 427: RachResourcesConfigMsg prachInfo.PrachFpach OK %d
Line 437: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->numOfAsc out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 450: Warning: RachResourcesConfigMsg accessServiceClassArray[n - 1].availableSYNC_UlCodesIndicesBitmask out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 455: Warning: RachResourcesConfigMsg accessServiceClassArray[n - 1].subchannelSize.choice out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 460: Warning: RachResourcesConfigMsg accessServiceClassArray[n - 1].subchannelSize.AvailSubChannelBitString out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 468: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.trChId out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 473: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.trChType out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 479: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.tti out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 484: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.channelCoding out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 489: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.rateMatchingArgument out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 494: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.crcSize out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
Line 499: Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.codingRate out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/TL1/TL1C/ChMgt/rach/src/tphy_CRachResources.c Line %d
