Line 84: [RFCTRL] Read MSpeedy0: EXCEPTION CASE FIFO NOT CLEARED (M_SW_DATA_GEN_FULL0 : %d) !!!!!!!
Line 114: [RFCTRL] Read MSpeedy0: EXCEPTION CASE FIFO NOT CLEARED (M_SW_DATA_GEN_STATUS0 : %d, ing) !!!!!!!
Line 138: [RFCTRL] Read MSpeedy0: EXCEPTION CASE FIFO NOT CLEARED (M_SW_DATA_GEN_STATUS0 : %d, done) !!!!!!!
Line 181: [RFCTRL] Write MSpeedy0: EXCEPTION CASE FIFO NOT CLEARED (%d) !!!!!!!
