Line 94: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 94: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 105: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 105: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 180: S0  ### Critical Error UmtsMessagePtr mMsg  = NULL (%d)
Line 180: S0  ### Critical Error UmtsMessagePtr mMsg  = NULL (%d)
Line 241: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d)
Line 241: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d)
Line 254: S0  ### Critical Error eutraCellSearchResultsList  = NULL (%d)
Line 254: S0  ### Critical Error eutraCellSearchResultsList  = NULL (%d)
Line 265: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
Line 265: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
