Line 92: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: EARFCN (%d), numOfEutraCells (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 92: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: EARFCN (%d), numOfEutraCells (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 103: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: cellId=%d, start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 103: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: cellId=%d, start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 184: S0  ### Critical Error UmtsMessagePtr mMsg = NULL (%d)
Line 184: S0  ### Critical Error UmtsMessagePtr mMsg = NULL (%d)
Line 242: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d), RSRP (%d), RSRQ (%d)
Line 242: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d), RSRP (%d), RSRQ (%d)
Line 257: S0  ### Critical Error eutraCellMeasResultsList = NULL (%d)
Line 257: S0  ### Critical Error eutraCellMeasResultsList = NULL (%d)
Line 266: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
Line 266: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
